export interface MinorTranspositionMatrixRow {
  readonly sourceTonic: string;
  readonly step: number;
  readonly targetChroma: number;
  readonly expected:
    | {
        readonly status: 'ready';
        readonly mode: 'minor';
        readonly sourceTonic: string;
        readonly targetTonic: string;
      }
    | {
        readonly status: 'requiresEnharmonicChoice';
        readonly mode: 'minor';
        readonly sourceTonic: string;
        readonly options: readonly string[];
      };
}

/**
 * AC5:n eksplisiittinen tarkastusmatriisi:
 * 15 mollitoonikkaa x 23 sallittua askelta = 345 riviä.
 */
export const MINOR_TRANSPOSITION_MATRIX: readonly MinorTranspositionMatrixRow[] = [
  { sourceTonic: 'C', step: -11, targetChroma: 1, expected: { status: 'ready', mode: 'minor', sourceTonic: 'C', targetTonic: 'C#' } },
  { sourceTonic: 'C', step: -10, targetChroma: 2, expected: { status: 'ready', mode: 'minor', sourceTonic: 'C', targetTonic: 'D' } },
  { sourceTonic: 'C', step: -9, targetChroma: 3, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'C', options: ['D#', 'Eb'] } },
  { sourceTonic: 'C', step: -8, targetChroma: 4, expected: { status: 'ready', mode: 'minor', sourceTonic: 'C', targetTonic: 'E' } },
  { sourceTonic: 'C', step: -7, targetChroma: 5, expected: { status: 'ready', mode: 'minor', sourceTonic: 'C', targetTonic: 'F' } },
  { sourceTonic: 'C', step: -6, targetChroma: 6, expected: { status: 'ready', mode: 'minor', sourceTonic: 'C', targetTonic: 'F#' } },
  { sourceTonic: 'C', step: -5, targetChroma: 7, expected: { status: 'ready', mode: 'minor', sourceTonic: 'C', targetTonic: 'G' } },
  { sourceTonic: 'C', step: -4, targetChroma: 8, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'C', options: ['G#', 'Ab'] } },
  { sourceTonic: 'C', step: -3, targetChroma: 9, expected: { status: 'ready', mode: 'minor', sourceTonic: 'C', targetTonic: 'A' } },
  { sourceTonic: 'C', step: -2, targetChroma: 10, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'C', options: ['A#', 'Bb'] } },
  { sourceTonic: 'C', step: -1, targetChroma: 11, expected: { status: 'ready', mode: 'minor', sourceTonic: 'C', targetTonic: 'B' } },
  { sourceTonic: 'C', step: 0, targetChroma: 0, expected: { status: 'ready', mode: 'minor', sourceTonic: 'C', targetTonic: 'C' } },
  { sourceTonic: 'C', step: 1, targetChroma: 1, expected: { status: 'ready', mode: 'minor', sourceTonic: 'C', targetTonic: 'C#' } },
  { sourceTonic: 'C', step: 2, targetChroma: 2, expected: { status: 'ready', mode: 'minor', sourceTonic: 'C', targetTonic: 'D' } },
  { sourceTonic: 'C', step: 3, targetChroma: 3, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'C', options: ['D#', 'Eb'] } },
  { sourceTonic: 'C', step: 4, targetChroma: 4, expected: { status: 'ready', mode: 'minor', sourceTonic: 'C', targetTonic: 'E' } },
  { sourceTonic: 'C', step: 5, targetChroma: 5, expected: { status: 'ready', mode: 'minor', sourceTonic: 'C', targetTonic: 'F' } },
  { sourceTonic: 'C', step: 6, targetChroma: 6, expected: { status: 'ready', mode: 'minor', sourceTonic: 'C', targetTonic: 'F#' } },
  { sourceTonic: 'C', step: 7, targetChroma: 7, expected: { status: 'ready', mode: 'minor', sourceTonic: 'C', targetTonic: 'G' } },
  { sourceTonic: 'C', step: 8, targetChroma: 8, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'C', options: ['G#', 'Ab'] } },
  { sourceTonic: 'C', step: 9, targetChroma: 9, expected: { status: 'ready', mode: 'minor', sourceTonic: 'C', targetTonic: 'A' } },
  { sourceTonic: 'C', step: 10, targetChroma: 10, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'C', options: ['A#', 'Bb'] } },
  { sourceTonic: 'C', step: 11, targetChroma: 11, expected: { status: 'ready', mode: 'minor', sourceTonic: 'C', targetTonic: 'B' } },
  { sourceTonic: 'C#', step: -11, targetChroma: 2, expected: { status: 'ready', mode: 'minor', sourceTonic: 'C#', targetTonic: 'D' } },
  { sourceTonic: 'C#', step: -10, targetChroma: 3, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'C#', options: ['D#', 'Eb'] } },
  { sourceTonic: 'C#', step: -9, targetChroma: 4, expected: { status: 'ready', mode: 'minor', sourceTonic: 'C#', targetTonic: 'E' } },
  { sourceTonic: 'C#', step: -8, targetChroma: 5, expected: { status: 'ready', mode: 'minor', sourceTonic: 'C#', targetTonic: 'F' } },
  { sourceTonic: 'C#', step: -7, targetChroma: 6, expected: { status: 'ready', mode: 'minor', sourceTonic: 'C#', targetTonic: 'F#' } },
  { sourceTonic: 'C#', step: -6, targetChroma: 7, expected: { status: 'ready', mode: 'minor', sourceTonic: 'C#', targetTonic: 'G' } },
  { sourceTonic: 'C#', step: -5, targetChroma: 8, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'C#', options: ['G#', 'Ab'] } },
  { sourceTonic: 'C#', step: -4, targetChroma: 9, expected: { status: 'ready', mode: 'minor', sourceTonic: 'C#', targetTonic: 'A' } },
  { sourceTonic: 'C#', step: -3, targetChroma: 10, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'C#', options: ['A#', 'Bb'] } },
  { sourceTonic: 'C#', step: -2, targetChroma: 11, expected: { status: 'ready', mode: 'minor', sourceTonic: 'C#', targetTonic: 'B' } },
  { sourceTonic: 'C#', step: -1, targetChroma: 0, expected: { status: 'ready', mode: 'minor', sourceTonic: 'C#', targetTonic: 'C' } },
  { sourceTonic: 'C#', step: 0, targetChroma: 1, expected: { status: 'ready', mode: 'minor', sourceTonic: 'C#', targetTonic: 'C#' } },
  { sourceTonic: 'C#', step: 1, targetChroma: 2, expected: { status: 'ready', mode: 'minor', sourceTonic: 'C#', targetTonic: 'D' } },
  { sourceTonic: 'C#', step: 2, targetChroma: 3, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'C#', options: ['D#', 'Eb'] } },
  { sourceTonic: 'C#', step: 3, targetChroma: 4, expected: { status: 'ready', mode: 'minor', sourceTonic: 'C#', targetTonic: 'E' } },
  { sourceTonic: 'C#', step: 4, targetChroma: 5, expected: { status: 'ready', mode: 'minor', sourceTonic: 'C#', targetTonic: 'F' } },
  { sourceTonic: 'C#', step: 5, targetChroma: 6, expected: { status: 'ready', mode: 'minor', sourceTonic: 'C#', targetTonic: 'F#' } },
  { sourceTonic: 'C#', step: 6, targetChroma: 7, expected: { status: 'ready', mode: 'minor', sourceTonic: 'C#', targetTonic: 'G' } },
  { sourceTonic: 'C#', step: 7, targetChroma: 8, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'C#', options: ['G#', 'Ab'] } },
  { sourceTonic: 'C#', step: 8, targetChroma: 9, expected: { status: 'ready', mode: 'minor', sourceTonic: 'C#', targetTonic: 'A' } },
  { sourceTonic: 'C#', step: 9, targetChroma: 10, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'C#', options: ['A#', 'Bb'] } },
  { sourceTonic: 'C#', step: 10, targetChroma: 11, expected: { status: 'ready', mode: 'minor', sourceTonic: 'C#', targetTonic: 'B' } },
  { sourceTonic: 'C#', step: 11, targetChroma: 0, expected: { status: 'ready', mode: 'minor', sourceTonic: 'C#', targetTonic: 'C' } },
  { sourceTonic: 'D', step: -11, targetChroma: 3, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'D', options: ['D#', 'Eb'] } },
  { sourceTonic: 'D', step: -10, targetChroma: 4, expected: { status: 'ready', mode: 'minor', sourceTonic: 'D', targetTonic: 'E' } },
  { sourceTonic: 'D', step: -9, targetChroma: 5, expected: { status: 'ready', mode: 'minor', sourceTonic: 'D', targetTonic: 'F' } },
  { sourceTonic: 'D', step: -8, targetChroma: 6, expected: { status: 'ready', mode: 'minor', sourceTonic: 'D', targetTonic: 'F#' } },
  { sourceTonic: 'D', step: -7, targetChroma: 7, expected: { status: 'ready', mode: 'minor', sourceTonic: 'D', targetTonic: 'G' } },
  { sourceTonic: 'D', step: -6, targetChroma: 8, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'D', options: ['G#', 'Ab'] } },
  { sourceTonic: 'D', step: -5, targetChroma: 9, expected: { status: 'ready', mode: 'minor', sourceTonic: 'D', targetTonic: 'A' } },
  { sourceTonic: 'D', step: -4, targetChroma: 10, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'D', options: ['A#', 'Bb'] } },
  { sourceTonic: 'D', step: -3, targetChroma: 11, expected: { status: 'ready', mode: 'minor', sourceTonic: 'D', targetTonic: 'B' } },
  { sourceTonic: 'D', step: -2, targetChroma: 0, expected: { status: 'ready', mode: 'minor', sourceTonic: 'D', targetTonic: 'C' } },
  { sourceTonic: 'D', step: -1, targetChroma: 1, expected: { status: 'ready', mode: 'minor', sourceTonic: 'D', targetTonic: 'C#' } },
  { sourceTonic: 'D', step: 0, targetChroma: 2, expected: { status: 'ready', mode: 'minor', sourceTonic: 'D', targetTonic: 'D' } },
  { sourceTonic: 'D', step: 1, targetChroma: 3, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'D', options: ['D#', 'Eb'] } },
  { sourceTonic: 'D', step: 2, targetChroma: 4, expected: { status: 'ready', mode: 'minor', sourceTonic: 'D', targetTonic: 'E' } },
  { sourceTonic: 'D', step: 3, targetChroma: 5, expected: { status: 'ready', mode: 'minor', sourceTonic: 'D', targetTonic: 'F' } },
  { sourceTonic: 'D', step: 4, targetChroma: 6, expected: { status: 'ready', mode: 'minor', sourceTonic: 'D', targetTonic: 'F#' } },
  { sourceTonic: 'D', step: 5, targetChroma: 7, expected: { status: 'ready', mode: 'minor', sourceTonic: 'D', targetTonic: 'G' } },
  { sourceTonic: 'D', step: 6, targetChroma: 8, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'D', options: ['G#', 'Ab'] } },
  { sourceTonic: 'D', step: 7, targetChroma: 9, expected: { status: 'ready', mode: 'minor', sourceTonic: 'D', targetTonic: 'A' } },
  { sourceTonic: 'D', step: 8, targetChroma: 10, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'D', options: ['A#', 'Bb'] } },
  { sourceTonic: 'D', step: 9, targetChroma: 11, expected: { status: 'ready', mode: 'minor', sourceTonic: 'D', targetTonic: 'B' } },
  { sourceTonic: 'D', step: 10, targetChroma: 0, expected: { status: 'ready', mode: 'minor', sourceTonic: 'D', targetTonic: 'C' } },
  { sourceTonic: 'D', step: 11, targetChroma: 1, expected: { status: 'ready', mode: 'minor', sourceTonic: 'D', targetTonic: 'C#' } },
  { sourceTonic: 'D#', step: -11, targetChroma: 4, expected: { status: 'ready', mode: 'minor', sourceTonic: 'D#', targetTonic: 'E' } },
  { sourceTonic: 'D#', step: -10, targetChroma: 5, expected: { status: 'ready', mode: 'minor', sourceTonic: 'D#', targetTonic: 'F' } },
  { sourceTonic: 'D#', step: -9, targetChroma: 6, expected: { status: 'ready', mode: 'minor', sourceTonic: 'D#', targetTonic: 'F#' } },
  { sourceTonic: 'D#', step: -8, targetChroma: 7, expected: { status: 'ready', mode: 'minor', sourceTonic: 'D#', targetTonic: 'G' } },
  { sourceTonic: 'D#', step: -7, targetChroma: 8, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'D#', options: ['G#', 'Ab'] } },
  { sourceTonic: 'D#', step: -6, targetChroma: 9, expected: { status: 'ready', mode: 'minor', sourceTonic: 'D#', targetTonic: 'A' } },
  { sourceTonic: 'D#', step: -5, targetChroma: 10, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'D#', options: ['A#', 'Bb'] } },
  { sourceTonic: 'D#', step: -4, targetChroma: 11, expected: { status: 'ready', mode: 'minor', sourceTonic: 'D#', targetTonic: 'B' } },
  { sourceTonic: 'D#', step: -3, targetChroma: 0, expected: { status: 'ready', mode: 'minor', sourceTonic: 'D#', targetTonic: 'C' } },
  { sourceTonic: 'D#', step: -2, targetChroma: 1, expected: { status: 'ready', mode: 'minor', sourceTonic: 'D#', targetTonic: 'C#' } },
  { sourceTonic: 'D#', step: -1, targetChroma: 2, expected: { status: 'ready', mode: 'minor', sourceTonic: 'D#', targetTonic: 'D' } },
  { sourceTonic: 'D#', step: 0, targetChroma: 3, expected: { status: 'ready', mode: 'minor', sourceTonic: 'D#', targetTonic: 'D#' } },
  { sourceTonic: 'D#', step: 1, targetChroma: 4, expected: { status: 'ready', mode: 'minor', sourceTonic: 'D#', targetTonic: 'E' } },
  { sourceTonic: 'D#', step: 2, targetChroma: 5, expected: { status: 'ready', mode: 'minor', sourceTonic: 'D#', targetTonic: 'F' } },
  { sourceTonic: 'D#', step: 3, targetChroma: 6, expected: { status: 'ready', mode: 'minor', sourceTonic: 'D#', targetTonic: 'F#' } },
  { sourceTonic: 'D#', step: 4, targetChroma: 7, expected: { status: 'ready', mode: 'minor', sourceTonic: 'D#', targetTonic: 'G' } },
  { sourceTonic: 'D#', step: 5, targetChroma: 8, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'D#', options: ['G#', 'Ab'] } },
  { sourceTonic: 'D#', step: 6, targetChroma: 9, expected: { status: 'ready', mode: 'minor', sourceTonic: 'D#', targetTonic: 'A' } },
  { sourceTonic: 'D#', step: 7, targetChroma: 10, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'D#', options: ['A#', 'Bb'] } },
  { sourceTonic: 'D#', step: 8, targetChroma: 11, expected: { status: 'ready', mode: 'minor', sourceTonic: 'D#', targetTonic: 'B' } },
  { sourceTonic: 'D#', step: 9, targetChroma: 0, expected: { status: 'ready', mode: 'minor', sourceTonic: 'D#', targetTonic: 'C' } },
  { sourceTonic: 'D#', step: 10, targetChroma: 1, expected: { status: 'ready', mode: 'minor', sourceTonic: 'D#', targetTonic: 'C#' } },
  { sourceTonic: 'D#', step: 11, targetChroma: 2, expected: { status: 'ready', mode: 'minor', sourceTonic: 'D#', targetTonic: 'D' } },
  { sourceTonic: 'Eb', step: -11, targetChroma: 4, expected: { status: 'ready', mode: 'minor', sourceTonic: 'Eb', targetTonic: 'E' } },
  { sourceTonic: 'Eb', step: -10, targetChroma: 5, expected: { status: 'ready', mode: 'minor', sourceTonic: 'Eb', targetTonic: 'F' } },
  { sourceTonic: 'Eb', step: -9, targetChroma: 6, expected: { status: 'ready', mode: 'minor', sourceTonic: 'Eb', targetTonic: 'F#' } },
  { sourceTonic: 'Eb', step: -8, targetChroma: 7, expected: { status: 'ready', mode: 'minor', sourceTonic: 'Eb', targetTonic: 'G' } },
  { sourceTonic: 'Eb', step: -7, targetChroma: 8, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'Eb', options: ['G#', 'Ab'] } },
  { sourceTonic: 'Eb', step: -6, targetChroma: 9, expected: { status: 'ready', mode: 'minor', sourceTonic: 'Eb', targetTonic: 'A' } },
  { sourceTonic: 'Eb', step: -5, targetChroma: 10, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'Eb', options: ['A#', 'Bb'] } },
  { sourceTonic: 'Eb', step: -4, targetChroma: 11, expected: { status: 'ready', mode: 'minor', sourceTonic: 'Eb', targetTonic: 'B' } },
  { sourceTonic: 'Eb', step: -3, targetChroma: 0, expected: { status: 'ready', mode: 'minor', sourceTonic: 'Eb', targetTonic: 'C' } },
  { sourceTonic: 'Eb', step: -2, targetChroma: 1, expected: { status: 'ready', mode: 'minor', sourceTonic: 'Eb', targetTonic: 'C#' } },
  { sourceTonic: 'Eb', step: -1, targetChroma: 2, expected: { status: 'ready', mode: 'minor', sourceTonic: 'Eb', targetTonic: 'D' } },
  { sourceTonic: 'Eb', step: 0, targetChroma: 3, expected: { status: 'ready', mode: 'minor', sourceTonic: 'Eb', targetTonic: 'Eb' } },
  { sourceTonic: 'Eb', step: 1, targetChroma: 4, expected: { status: 'ready', mode: 'minor', sourceTonic: 'Eb', targetTonic: 'E' } },
  { sourceTonic: 'Eb', step: 2, targetChroma: 5, expected: { status: 'ready', mode: 'minor', sourceTonic: 'Eb', targetTonic: 'F' } },
  { sourceTonic: 'Eb', step: 3, targetChroma: 6, expected: { status: 'ready', mode: 'minor', sourceTonic: 'Eb', targetTonic: 'F#' } },
  { sourceTonic: 'Eb', step: 4, targetChroma: 7, expected: { status: 'ready', mode: 'minor', sourceTonic: 'Eb', targetTonic: 'G' } },
  { sourceTonic: 'Eb', step: 5, targetChroma: 8, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'Eb', options: ['G#', 'Ab'] } },
  { sourceTonic: 'Eb', step: 6, targetChroma: 9, expected: { status: 'ready', mode: 'minor', sourceTonic: 'Eb', targetTonic: 'A' } },
  { sourceTonic: 'Eb', step: 7, targetChroma: 10, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'Eb', options: ['A#', 'Bb'] } },
  { sourceTonic: 'Eb', step: 8, targetChroma: 11, expected: { status: 'ready', mode: 'minor', sourceTonic: 'Eb', targetTonic: 'B' } },
  { sourceTonic: 'Eb', step: 9, targetChroma: 0, expected: { status: 'ready', mode: 'minor', sourceTonic: 'Eb', targetTonic: 'C' } },
  { sourceTonic: 'Eb', step: 10, targetChroma: 1, expected: { status: 'ready', mode: 'minor', sourceTonic: 'Eb', targetTonic: 'C#' } },
  { sourceTonic: 'Eb', step: 11, targetChroma: 2, expected: { status: 'ready', mode: 'minor', sourceTonic: 'Eb', targetTonic: 'D' } },
  { sourceTonic: 'E', step: -11, targetChroma: 5, expected: { status: 'ready', mode: 'minor', sourceTonic: 'E', targetTonic: 'F' } },
  { sourceTonic: 'E', step: -10, targetChroma: 6, expected: { status: 'ready', mode: 'minor', sourceTonic: 'E', targetTonic: 'F#' } },
  { sourceTonic: 'E', step: -9, targetChroma: 7, expected: { status: 'ready', mode: 'minor', sourceTonic: 'E', targetTonic: 'G' } },
  { sourceTonic: 'E', step: -8, targetChroma: 8, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'E', options: ['G#', 'Ab'] } },
  { sourceTonic: 'E', step: -7, targetChroma: 9, expected: { status: 'ready', mode: 'minor', sourceTonic: 'E', targetTonic: 'A' } },
  { sourceTonic: 'E', step: -6, targetChroma: 10, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'E', options: ['A#', 'Bb'] } },
  { sourceTonic: 'E', step: -5, targetChroma: 11, expected: { status: 'ready', mode: 'minor', sourceTonic: 'E', targetTonic: 'B' } },
  { sourceTonic: 'E', step: -4, targetChroma: 0, expected: { status: 'ready', mode: 'minor', sourceTonic: 'E', targetTonic: 'C' } },
  { sourceTonic: 'E', step: -3, targetChroma: 1, expected: { status: 'ready', mode: 'minor', sourceTonic: 'E', targetTonic: 'C#' } },
  { sourceTonic: 'E', step: -2, targetChroma: 2, expected: { status: 'ready', mode: 'minor', sourceTonic: 'E', targetTonic: 'D' } },
  { sourceTonic: 'E', step: -1, targetChroma: 3, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'E', options: ['D#', 'Eb'] } },
  { sourceTonic: 'E', step: 0, targetChroma: 4, expected: { status: 'ready', mode: 'minor', sourceTonic: 'E', targetTonic: 'E' } },
  { sourceTonic: 'E', step: 1, targetChroma: 5, expected: { status: 'ready', mode: 'minor', sourceTonic: 'E', targetTonic: 'F' } },
  { sourceTonic: 'E', step: 2, targetChroma: 6, expected: { status: 'ready', mode: 'minor', sourceTonic: 'E', targetTonic: 'F#' } },
  { sourceTonic: 'E', step: 3, targetChroma: 7, expected: { status: 'ready', mode: 'minor', sourceTonic: 'E', targetTonic: 'G' } },
  { sourceTonic: 'E', step: 4, targetChroma: 8, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'E', options: ['G#', 'Ab'] } },
  { sourceTonic: 'E', step: 5, targetChroma: 9, expected: { status: 'ready', mode: 'minor', sourceTonic: 'E', targetTonic: 'A' } },
  { sourceTonic: 'E', step: 6, targetChroma: 10, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'E', options: ['A#', 'Bb'] } },
  { sourceTonic: 'E', step: 7, targetChroma: 11, expected: { status: 'ready', mode: 'minor', sourceTonic: 'E', targetTonic: 'B' } },
  { sourceTonic: 'E', step: 8, targetChroma: 0, expected: { status: 'ready', mode: 'minor', sourceTonic: 'E', targetTonic: 'C' } },
  { sourceTonic: 'E', step: 9, targetChroma: 1, expected: { status: 'ready', mode: 'minor', sourceTonic: 'E', targetTonic: 'C#' } },
  { sourceTonic: 'E', step: 10, targetChroma: 2, expected: { status: 'ready', mode: 'minor', sourceTonic: 'E', targetTonic: 'D' } },
  { sourceTonic: 'E', step: 11, targetChroma: 3, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'E', options: ['D#', 'Eb'] } },
  { sourceTonic: 'F', step: -11, targetChroma: 6, expected: { status: 'ready', mode: 'minor', sourceTonic: 'F', targetTonic: 'F#' } },
  { sourceTonic: 'F', step: -10, targetChroma: 7, expected: { status: 'ready', mode: 'minor', sourceTonic: 'F', targetTonic: 'G' } },
  { sourceTonic: 'F', step: -9, targetChroma: 8, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'F', options: ['G#', 'Ab'] } },
  { sourceTonic: 'F', step: -8, targetChroma: 9, expected: { status: 'ready', mode: 'minor', sourceTonic: 'F', targetTonic: 'A' } },
  { sourceTonic: 'F', step: -7, targetChroma: 10, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'F', options: ['A#', 'Bb'] } },
  { sourceTonic: 'F', step: -6, targetChroma: 11, expected: { status: 'ready', mode: 'minor', sourceTonic: 'F', targetTonic: 'B' } },
  { sourceTonic: 'F', step: -5, targetChroma: 0, expected: { status: 'ready', mode: 'minor', sourceTonic: 'F', targetTonic: 'C' } },
  { sourceTonic: 'F', step: -4, targetChroma: 1, expected: { status: 'ready', mode: 'minor', sourceTonic: 'F', targetTonic: 'C#' } },
  { sourceTonic: 'F', step: -3, targetChroma: 2, expected: { status: 'ready', mode: 'minor', sourceTonic: 'F', targetTonic: 'D' } },
  { sourceTonic: 'F', step: -2, targetChroma: 3, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'F', options: ['D#', 'Eb'] } },
  { sourceTonic: 'F', step: -1, targetChroma: 4, expected: { status: 'ready', mode: 'minor', sourceTonic: 'F', targetTonic: 'E' } },
  { sourceTonic: 'F', step: 0, targetChroma: 5, expected: { status: 'ready', mode: 'minor', sourceTonic: 'F', targetTonic: 'F' } },
  { sourceTonic: 'F', step: 1, targetChroma: 6, expected: { status: 'ready', mode: 'minor', sourceTonic: 'F', targetTonic: 'F#' } },
  { sourceTonic: 'F', step: 2, targetChroma: 7, expected: { status: 'ready', mode: 'minor', sourceTonic: 'F', targetTonic: 'G' } },
  { sourceTonic: 'F', step: 3, targetChroma: 8, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'F', options: ['G#', 'Ab'] } },
  { sourceTonic: 'F', step: 4, targetChroma: 9, expected: { status: 'ready', mode: 'minor', sourceTonic: 'F', targetTonic: 'A' } },
  { sourceTonic: 'F', step: 5, targetChroma: 10, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'F', options: ['A#', 'Bb'] } },
  { sourceTonic: 'F', step: 6, targetChroma: 11, expected: { status: 'ready', mode: 'minor', sourceTonic: 'F', targetTonic: 'B' } },
  { sourceTonic: 'F', step: 7, targetChroma: 0, expected: { status: 'ready', mode: 'minor', sourceTonic: 'F', targetTonic: 'C' } },
  { sourceTonic: 'F', step: 8, targetChroma: 1, expected: { status: 'ready', mode: 'minor', sourceTonic: 'F', targetTonic: 'C#' } },
  { sourceTonic: 'F', step: 9, targetChroma: 2, expected: { status: 'ready', mode: 'minor', sourceTonic: 'F', targetTonic: 'D' } },
  { sourceTonic: 'F', step: 10, targetChroma: 3, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'F', options: ['D#', 'Eb'] } },
  { sourceTonic: 'F', step: 11, targetChroma: 4, expected: { status: 'ready', mode: 'minor', sourceTonic: 'F', targetTonic: 'E' } },
  { sourceTonic: 'F#', step: -11, targetChroma: 7, expected: { status: 'ready', mode: 'minor', sourceTonic: 'F#', targetTonic: 'G' } },
  { sourceTonic: 'F#', step: -10, targetChroma: 8, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'F#', options: ['G#', 'Ab'] } },
  { sourceTonic: 'F#', step: -9, targetChroma: 9, expected: { status: 'ready', mode: 'minor', sourceTonic: 'F#', targetTonic: 'A' } },
  { sourceTonic: 'F#', step: -8, targetChroma: 10, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'F#', options: ['A#', 'Bb'] } },
  { sourceTonic: 'F#', step: -7, targetChroma: 11, expected: { status: 'ready', mode: 'minor', sourceTonic: 'F#', targetTonic: 'B' } },
  { sourceTonic: 'F#', step: -6, targetChroma: 0, expected: { status: 'ready', mode: 'minor', sourceTonic: 'F#', targetTonic: 'C' } },
  { sourceTonic: 'F#', step: -5, targetChroma: 1, expected: { status: 'ready', mode: 'minor', sourceTonic: 'F#', targetTonic: 'C#' } },
  { sourceTonic: 'F#', step: -4, targetChroma: 2, expected: { status: 'ready', mode: 'minor', sourceTonic: 'F#', targetTonic: 'D' } },
  { sourceTonic: 'F#', step: -3, targetChroma: 3, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'F#', options: ['D#', 'Eb'] } },
  { sourceTonic: 'F#', step: -2, targetChroma: 4, expected: { status: 'ready', mode: 'minor', sourceTonic: 'F#', targetTonic: 'E' } },
  { sourceTonic: 'F#', step: -1, targetChroma: 5, expected: { status: 'ready', mode: 'minor', sourceTonic: 'F#', targetTonic: 'F' } },
  { sourceTonic: 'F#', step: 0, targetChroma: 6, expected: { status: 'ready', mode: 'minor', sourceTonic: 'F#', targetTonic: 'F#' } },
  { sourceTonic: 'F#', step: 1, targetChroma: 7, expected: { status: 'ready', mode: 'minor', sourceTonic: 'F#', targetTonic: 'G' } },
  { sourceTonic: 'F#', step: 2, targetChroma: 8, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'F#', options: ['G#', 'Ab'] } },
  { sourceTonic: 'F#', step: 3, targetChroma: 9, expected: { status: 'ready', mode: 'minor', sourceTonic: 'F#', targetTonic: 'A' } },
  { sourceTonic: 'F#', step: 4, targetChroma: 10, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'F#', options: ['A#', 'Bb'] } },
  { sourceTonic: 'F#', step: 5, targetChroma: 11, expected: { status: 'ready', mode: 'minor', sourceTonic: 'F#', targetTonic: 'B' } },
  { sourceTonic: 'F#', step: 6, targetChroma: 0, expected: { status: 'ready', mode: 'minor', sourceTonic: 'F#', targetTonic: 'C' } },
  { sourceTonic: 'F#', step: 7, targetChroma: 1, expected: { status: 'ready', mode: 'minor', sourceTonic: 'F#', targetTonic: 'C#' } },
  { sourceTonic: 'F#', step: 8, targetChroma: 2, expected: { status: 'ready', mode: 'minor', sourceTonic: 'F#', targetTonic: 'D' } },
  { sourceTonic: 'F#', step: 9, targetChroma: 3, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'F#', options: ['D#', 'Eb'] } },
  { sourceTonic: 'F#', step: 10, targetChroma: 4, expected: { status: 'ready', mode: 'minor', sourceTonic: 'F#', targetTonic: 'E' } },
  { sourceTonic: 'F#', step: 11, targetChroma: 5, expected: { status: 'ready', mode: 'minor', sourceTonic: 'F#', targetTonic: 'F' } },
  { sourceTonic: 'G', step: -11, targetChroma: 8, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'G', options: ['G#', 'Ab'] } },
  { sourceTonic: 'G', step: -10, targetChroma: 9, expected: { status: 'ready', mode: 'minor', sourceTonic: 'G', targetTonic: 'A' } },
  { sourceTonic: 'G', step: -9, targetChroma: 10, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'G', options: ['A#', 'Bb'] } },
  { sourceTonic: 'G', step: -8, targetChroma: 11, expected: { status: 'ready', mode: 'minor', sourceTonic: 'G', targetTonic: 'B' } },
  { sourceTonic: 'G', step: -7, targetChroma: 0, expected: { status: 'ready', mode: 'minor', sourceTonic: 'G', targetTonic: 'C' } },
  { sourceTonic: 'G', step: -6, targetChroma: 1, expected: { status: 'ready', mode: 'minor', sourceTonic: 'G', targetTonic: 'C#' } },
  { sourceTonic: 'G', step: -5, targetChroma: 2, expected: { status: 'ready', mode: 'minor', sourceTonic: 'G', targetTonic: 'D' } },
  { sourceTonic: 'G', step: -4, targetChroma: 3, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'G', options: ['D#', 'Eb'] } },
  { sourceTonic: 'G', step: -3, targetChroma: 4, expected: { status: 'ready', mode: 'minor', sourceTonic: 'G', targetTonic: 'E' } },
  { sourceTonic: 'G', step: -2, targetChroma: 5, expected: { status: 'ready', mode: 'minor', sourceTonic: 'G', targetTonic: 'F' } },
  { sourceTonic: 'G', step: -1, targetChroma: 6, expected: { status: 'ready', mode: 'minor', sourceTonic: 'G', targetTonic: 'F#' } },
  { sourceTonic: 'G', step: 0, targetChroma: 7, expected: { status: 'ready', mode: 'minor', sourceTonic: 'G', targetTonic: 'G' } },
  { sourceTonic: 'G', step: 1, targetChroma: 8, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'G', options: ['G#', 'Ab'] } },
  { sourceTonic: 'G', step: 2, targetChroma: 9, expected: { status: 'ready', mode: 'minor', sourceTonic: 'G', targetTonic: 'A' } },
  { sourceTonic: 'G', step: 3, targetChroma: 10, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'G', options: ['A#', 'Bb'] } },
  { sourceTonic: 'G', step: 4, targetChroma: 11, expected: { status: 'ready', mode: 'minor', sourceTonic: 'G', targetTonic: 'B' } },
  { sourceTonic: 'G', step: 5, targetChroma: 0, expected: { status: 'ready', mode: 'minor', sourceTonic: 'G', targetTonic: 'C' } },
  { sourceTonic: 'G', step: 6, targetChroma: 1, expected: { status: 'ready', mode: 'minor', sourceTonic: 'G', targetTonic: 'C#' } },
  { sourceTonic: 'G', step: 7, targetChroma: 2, expected: { status: 'ready', mode: 'minor', sourceTonic: 'G', targetTonic: 'D' } },
  { sourceTonic: 'G', step: 8, targetChroma: 3, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'G', options: ['D#', 'Eb'] } },
  { sourceTonic: 'G', step: 9, targetChroma: 4, expected: { status: 'ready', mode: 'minor', sourceTonic: 'G', targetTonic: 'E' } },
  { sourceTonic: 'G', step: 10, targetChroma: 5, expected: { status: 'ready', mode: 'minor', sourceTonic: 'G', targetTonic: 'F' } },
  { sourceTonic: 'G', step: 11, targetChroma: 6, expected: { status: 'ready', mode: 'minor', sourceTonic: 'G', targetTonic: 'F#' } },
  { sourceTonic: 'G#', step: -11, targetChroma: 9, expected: { status: 'ready', mode: 'minor', sourceTonic: 'G#', targetTonic: 'A' } },
  { sourceTonic: 'G#', step: -10, targetChroma: 10, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'G#', options: ['A#', 'Bb'] } },
  { sourceTonic: 'G#', step: -9, targetChroma: 11, expected: { status: 'ready', mode: 'minor', sourceTonic: 'G#', targetTonic: 'B' } },
  { sourceTonic: 'G#', step: -8, targetChroma: 0, expected: { status: 'ready', mode: 'minor', sourceTonic: 'G#', targetTonic: 'C' } },
  { sourceTonic: 'G#', step: -7, targetChroma: 1, expected: { status: 'ready', mode: 'minor', sourceTonic: 'G#', targetTonic: 'C#' } },
  { sourceTonic: 'G#', step: -6, targetChroma: 2, expected: { status: 'ready', mode: 'minor', sourceTonic: 'G#', targetTonic: 'D' } },
  { sourceTonic: 'G#', step: -5, targetChroma: 3, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'G#', options: ['D#', 'Eb'] } },
  { sourceTonic: 'G#', step: -4, targetChroma: 4, expected: { status: 'ready', mode: 'minor', sourceTonic: 'G#', targetTonic: 'E' } },
  { sourceTonic: 'G#', step: -3, targetChroma: 5, expected: { status: 'ready', mode: 'minor', sourceTonic: 'G#', targetTonic: 'F' } },
  { sourceTonic: 'G#', step: -2, targetChroma: 6, expected: { status: 'ready', mode: 'minor', sourceTonic: 'G#', targetTonic: 'F#' } },
  { sourceTonic: 'G#', step: -1, targetChroma: 7, expected: { status: 'ready', mode: 'minor', sourceTonic: 'G#', targetTonic: 'G' } },
  { sourceTonic: 'G#', step: 0, targetChroma: 8, expected: { status: 'ready', mode: 'minor', sourceTonic: 'G#', targetTonic: 'G#' } },
  { sourceTonic: 'G#', step: 1, targetChroma: 9, expected: { status: 'ready', mode: 'minor', sourceTonic: 'G#', targetTonic: 'A' } },
  { sourceTonic: 'G#', step: 2, targetChroma: 10, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'G#', options: ['A#', 'Bb'] } },
  { sourceTonic: 'G#', step: 3, targetChroma: 11, expected: { status: 'ready', mode: 'minor', sourceTonic: 'G#', targetTonic: 'B' } },
  { sourceTonic: 'G#', step: 4, targetChroma: 0, expected: { status: 'ready', mode: 'minor', sourceTonic: 'G#', targetTonic: 'C' } },
  { sourceTonic: 'G#', step: 5, targetChroma: 1, expected: { status: 'ready', mode: 'minor', sourceTonic: 'G#', targetTonic: 'C#' } },
  { sourceTonic: 'G#', step: 6, targetChroma: 2, expected: { status: 'ready', mode: 'minor', sourceTonic: 'G#', targetTonic: 'D' } },
  { sourceTonic: 'G#', step: 7, targetChroma: 3, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'G#', options: ['D#', 'Eb'] } },
  { sourceTonic: 'G#', step: 8, targetChroma: 4, expected: { status: 'ready', mode: 'minor', sourceTonic: 'G#', targetTonic: 'E' } },
  { sourceTonic: 'G#', step: 9, targetChroma: 5, expected: { status: 'ready', mode: 'minor', sourceTonic: 'G#', targetTonic: 'F' } },
  { sourceTonic: 'G#', step: 10, targetChroma: 6, expected: { status: 'ready', mode: 'minor', sourceTonic: 'G#', targetTonic: 'F#' } },
  { sourceTonic: 'G#', step: 11, targetChroma: 7, expected: { status: 'ready', mode: 'minor', sourceTonic: 'G#', targetTonic: 'G' } },
  { sourceTonic: 'Ab', step: -11, targetChroma: 9, expected: { status: 'ready', mode: 'minor', sourceTonic: 'Ab', targetTonic: 'A' } },
  { sourceTonic: 'Ab', step: -10, targetChroma: 10, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'Ab', options: ['A#', 'Bb'] } },
  { sourceTonic: 'Ab', step: -9, targetChroma: 11, expected: { status: 'ready', mode: 'minor', sourceTonic: 'Ab', targetTonic: 'B' } },
  { sourceTonic: 'Ab', step: -8, targetChroma: 0, expected: { status: 'ready', mode: 'minor', sourceTonic: 'Ab', targetTonic: 'C' } },
  { sourceTonic: 'Ab', step: -7, targetChroma: 1, expected: { status: 'ready', mode: 'minor', sourceTonic: 'Ab', targetTonic: 'C#' } },
  { sourceTonic: 'Ab', step: -6, targetChroma: 2, expected: { status: 'ready', mode: 'minor', sourceTonic: 'Ab', targetTonic: 'D' } },
  { sourceTonic: 'Ab', step: -5, targetChroma: 3, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'Ab', options: ['D#', 'Eb'] } },
  { sourceTonic: 'Ab', step: -4, targetChroma: 4, expected: { status: 'ready', mode: 'minor', sourceTonic: 'Ab', targetTonic: 'E' } },
  { sourceTonic: 'Ab', step: -3, targetChroma: 5, expected: { status: 'ready', mode: 'minor', sourceTonic: 'Ab', targetTonic: 'F' } },
  { sourceTonic: 'Ab', step: -2, targetChroma: 6, expected: { status: 'ready', mode: 'minor', sourceTonic: 'Ab', targetTonic: 'F#' } },
  { sourceTonic: 'Ab', step: -1, targetChroma: 7, expected: { status: 'ready', mode: 'minor', sourceTonic: 'Ab', targetTonic: 'G' } },
  { sourceTonic: 'Ab', step: 0, targetChroma: 8, expected: { status: 'ready', mode: 'minor', sourceTonic: 'Ab', targetTonic: 'Ab' } },
  { sourceTonic: 'Ab', step: 1, targetChroma: 9, expected: { status: 'ready', mode: 'minor', sourceTonic: 'Ab', targetTonic: 'A' } },
  { sourceTonic: 'Ab', step: 2, targetChroma: 10, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'Ab', options: ['A#', 'Bb'] } },
  { sourceTonic: 'Ab', step: 3, targetChroma: 11, expected: { status: 'ready', mode: 'minor', sourceTonic: 'Ab', targetTonic: 'B' } },
  { sourceTonic: 'Ab', step: 4, targetChroma: 0, expected: { status: 'ready', mode: 'minor', sourceTonic: 'Ab', targetTonic: 'C' } },
  { sourceTonic: 'Ab', step: 5, targetChroma: 1, expected: { status: 'ready', mode: 'minor', sourceTonic: 'Ab', targetTonic: 'C#' } },
  { sourceTonic: 'Ab', step: 6, targetChroma: 2, expected: { status: 'ready', mode: 'minor', sourceTonic: 'Ab', targetTonic: 'D' } },
  { sourceTonic: 'Ab', step: 7, targetChroma: 3, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'Ab', options: ['D#', 'Eb'] } },
  { sourceTonic: 'Ab', step: 8, targetChroma: 4, expected: { status: 'ready', mode: 'minor', sourceTonic: 'Ab', targetTonic: 'E' } },
  { sourceTonic: 'Ab', step: 9, targetChroma: 5, expected: { status: 'ready', mode: 'minor', sourceTonic: 'Ab', targetTonic: 'F' } },
  { sourceTonic: 'Ab', step: 10, targetChroma: 6, expected: { status: 'ready', mode: 'minor', sourceTonic: 'Ab', targetTonic: 'F#' } },
  { sourceTonic: 'Ab', step: 11, targetChroma: 7, expected: { status: 'ready', mode: 'minor', sourceTonic: 'Ab', targetTonic: 'G' } },
  { sourceTonic: 'A', step: -11, targetChroma: 10, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'A', options: ['A#', 'Bb'] } },
  { sourceTonic: 'A', step: -10, targetChroma: 11, expected: { status: 'ready', mode: 'minor', sourceTonic: 'A', targetTonic: 'B' } },
  { sourceTonic: 'A', step: -9, targetChroma: 0, expected: { status: 'ready', mode: 'minor', sourceTonic: 'A', targetTonic: 'C' } },
  { sourceTonic: 'A', step: -8, targetChroma: 1, expected: { status: 'ready', mode: 'minor', sourceTonic: 'A', targetTonic: 'C#' } },
  { sourceTonic: 'A', step: -7, targetChroma: 2, expected: { status: 'ready', mode: 'minor', sourceTonic: 'A', targetTonic: 'D' } },
  { sourceTonic: 'A', step: -6, targetChroma: 3, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'A', options: ['D#', 'Eb'] } },
  { sourceTonic: 'A', step: -5, targetChroma: 4, expected: { status: 'ready', mode: 'minor', sourceTonic: 'A', targetTonic: 'E' } },
  { sourceTonic: 'A', step: -4, targetChroma: 5, expected: { status: 'ready', mode: 'minor', sourceTonic: 'A', targetTonic: 'F' } },
  { sourceTonic: 'A', step: -3, targetChroma: 6, expected: { status: 'ready', mode: 'minor', sourceTonic: 'A', targetTonic: 'F#' } },
  { sourceTonic: 'A', step: -2, targetChroma: 7, expected: { status: 'ready', mode: 'minor', sourceTonic: 'A', targetTonic: 'G' } },
  { sourceTonic: 'A', step: -1, targetChroma: 8, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'A', options: ['G#', 'Ab'] } },
  { sourceTonic: 'A', step: 0, targetChroma: 9, expected: { status: 'ready', mode: 'minor', sourceTonic: 'A', targetTonic: 'A' } },
  { sourceTonic: 'A', step: 1, targetChroma: 10, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'A', options: ['A#', 'Bb'] } },
  { sourceTonic: 'A', step: 2, targetChroma: 11, expected: { status: 'ready', mode: 'minor', sourceTonic: 'A', targetTonic: 'B' } },
  { sourceTonic: 'A', step: 3, targetChroma: 0, expected: { status: 'ready', mode: 'minor', sourceTonic: 'A', targetTonic: 'C' } },
  { sourceTonic: 'A', step: 4, targetChroma: 1, expected: { status: 'ready', mode: 'minor', sourceTonic: 'A', targetTonic: 'C#' } },
  { sourceTonic: 'A', step: 5, targetChroma: 2, expected: { status: 'ready', mode: 'minor', sourceTonic: 'A', targetTonic: 'D' } },
  { sourceTonic: 'A', step: 6, targetChroma: 3, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'A', options: ['D#', 'Eb'] } },
  { sourceTonic: 'A', step: 7, targetChroma: 4, expected: { status: 'ready', mode: 'minor', sourceTonic: 'A', targetTonic: 'E' } },
  { sourceTonic: 'A', step: 8, targetChroma: 5, expected: { status: 'ready', mode: 'minor', sourceTonic: 'A', targetTonic: 'F' } },
  { sourceTonic: 'A', step: 9, targetChroma: 6, expected: { status: 'ready', mode: 'minor', sourceTonic: 'A', targetTonic: 'F#' } },
  { sourceTonic: 'A', step: 10, targetChroma: 7, expected: { status: 'ready', mode: 'minor', sourceTonic: 'A', targetTonic: 'G' } },
  { sourceTonic: 'A', step: 11, targetChroma: 8, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'A', options: ['G#', 'Ab'] } },
  { sourceTonic: 'A#', step: -11, targetChroma: 11, expected: { status: 'ready', mode: 'minor', sourceTonic: 'A#', targetTonic: 'B' } },
  { sourceTonic: 'A#', step: -10, targetChroma: 0, expected: { status: 'ready', mode: 'minor', sourceTonic: 'A#', targetTonic: 'C' } },
  { sourceTonic: 'A#', step: -9, targetChroma: 1, expected: { status: 'ready', mode: 'minor', sourceTonic: 'A#', targetTonic: 'C#' } },
  { sourceTonic: 'A#', step: -8, targetChroma: 2, expected: { status: 'ready', mode: 'minor', sourceTonic: 'A#', targetTonic: 'D' } },
  { sourceTonic: 'A#', step: -7, targetChroma: 3, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'A#', options: ['D#', 'Eb'] } },
  { sourceTonic: 'A#', step: -6, targetChroma: 4, expected: { status: 'ready', mode: 'minor', sourceTonic: 'A#', targetTonic: 'E' } },
  { sourceTonic: 'A#', step: -5, targetChroma: 5, expected: { status: 'ready', mode: 'minor', sourceTonic: 'A#', targetTonic: 'F' } },
  { sourceTonic: 'A#', step: -4, targetChroma: 6, expected: { status: 'ready', mode: 'minor', sourceTonic: 'A#', targetTonic: 'F#' } },
  { sourceTonic: 'A#', step: -3, targetChroma: 7, expected: { status: 'ready', mode: 'minor', sourceTonic: 'A#', targetTonic: 'G' } },
  { sourceTonic: 'A#', step: -2, targetChroma: 8, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'A#', options: ['G#', 'Ab'] } },
  { sourceTonic: 'A#', step: -1, targetChroma: 9, expected: { status: 'ready', mode: 'minor', sourceTonic: 'A#', targetTonic: 'A' } },
  { sourceTonic: 'A#', step: 0, targetChroma: 10, expected: { status: 'ready', mode: 'minor', sourceTonic: 'A#', targetTonic: 'A#' } },
  { sourceTonic: 'A#', step: 1, targetChroma: 11, expected: { status: 'ready', mode: 'minor', sourceTonic: 'A#', targetTonic: 'B' } },
  { sourceTonic: 'A#', step: 2, targetChroma: 0, expected: { status: 'ready', mode: 'minor', sourceTonic: 'A#', targetTonic: 'C' } },
  { sourceTonic: 'A#', step: 3, targetChroma: 1, expected: { status: 'ready', mode: 'minor', sourceTonic: 'A#', targetTonic: 'C#' } },
  { sourceTonic: 'A#', step: 4, targetChroma: 2, expected: { status: 'ready', mode: 'minor', sourceTonic: 'A#', targetTonic: 'D' } },
  { sourceTonic: 'A#', step: 5, targetChroma: 3, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'A#', options: ['D#', 'Eb'] } },
  { sourceTonic: 'A#', step: 6, targetChroma: 4, expected: { status: 'ready', mode: 'minor', sourceTonic: 'A#', targetTonic: 'E' } },
  { sourceTonic: 'A#', step: 7, targetChroma: 5, expected: { status: 'ready', mode: 'minor', sourceTonic: 'A#', targetTonic: 'F' } },
  { sourceTonic: 'A#', step: 8, targetChroma: 6, expected: { status: 'ready', mode: 'minor', sourceTonic: 'A#', targetTonic: 'F#' } },
  { sourceTonic: 'A#', step: 9, targetChroma: 7, expected: { status: 'ready', mode: 'minor', sourceTonic: 'A#', targetTonic: 'G' } },
  { sourceTonic: 'A#', step: 10, targetChroma: 8, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'A#', options: ['G#', 'Ab'] } },
  { sourceTonic: 'A#', step: 11, targetChroma: 9, expected: { status: 'ready', mode: 'minor', sourceTonic: 'A#', targetTonic: 'A' } },
  { sourceTonic: 'Bb', step: -11, targetChroma: 11, expected: { status: 'ready', mode: 'minor', sourceTonic: 'Bb', targetTonic: 'B' } },
  { sourceTonic: 'Bb', step: -10, targetChroma: 0, expected: { status: 'ready', mode: 'minor', sourceTonic: 'Bb', targetTonic: 'C' } },
  { sourceTonic: 'Bb', step: -9, targetChroma: 1, expected: { status: 'ready', mode: 'minor', sourceTonic: 'Bb', targetTonic: 'C#' } },
  { sourceTonic: 'Bb', step: -8, targetChroma: 2, expected: { status: 'ready', mode: 'minor', sourceTonic: 'Bb', targetTonic: 'D' } },
  { sourceTonic: 'Bb', step: -7, targetChroma: 3, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'Bb', options: ['D#', 'Eb'] } },
  { sourceTonic: 'Bb', step: -6, targetChroma: 4, expected: { status: 'ready', mode: 'minor', sourceTonic: 'Bb', targetTonic: 'E' } },
  { sourceTonic: 'Bb', step: -5, targetChroma: 5, expected: { status: 'ready', mode: 'minor', sourceTonic: 'Bb', targetTonic: 'F' } },
  { sourceTonic: 'Bb', step: -4, targetChroma: 6, expected: { status: 'ready', mode: 'minor', sourceTonic: 'Bb', targetTonic: 'F#' } },
  { sourceTonic: 'Bb', step: -3, targetChroma: 7, expected: { status: 'ready', mode: 'minor', sourceTonic: 'Bb', targetTonic: 'G' } },
  { sourceTonic: 'Bb', step: -2, targetChroma: 8, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'Bb', options: ['G#', 'Ab'] } },
  { sourceTonic: 'Bb', step: -1, targetChroma: 9, expected: { status: 'ready', mode: 'minor', sourceTonic: 'Bb', targetTonic: 'A' } },
  { sourceTonic: 'Bb', step: 0, targetChroma: 10, expected: { status: 'ready', mode: 'minor', sourceTonic: 'Bb', targetTonic: 'Bb' } },
  { sourceTonic: 'Bb', step: 1, targetChroma: 11, expected: { status: 'ready', mode: 'minor', sourceTonic: 'Bb', targetTonic: 'B' } },
  { sourceTonic: 'Bb', step: 2, targetChroma: 0, expected: { status: 'ready', mode: 'minor', sourceTonic: 'Bb', targetTonic: 'C' } },
  { sourceTonic: 'Bb', step: 3, targetChroma: 1, expected: { status: 'ready', mode: 'minor', sourceTonic: 'Bb', targetTonic: 'C#' } },
  { sourceTonic: 'Bb', step: 4, targetChroma: 2, expected: { status: 'ready', mode: 'minor', sourceTonic: 'Bb', targetTonic: 'D' } },
  { sourceTonic: 'Bb', step: 5, targetChroma: 3, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'Bb', options: ['D#', 'Eb'] } },
  { sourceTonic: 'Bb', step: 6, targetChroma: 4, expected: { status: 'ready', mode: 'minor', sourceTonic: 'Bb', targetTonic: 'E' } },
  { sourceTonic: 'Bb', step: 7, targetChroma: 5, expected: { status: 'ready', mode: 'minor', sourceTonic: 'Bb', targetTonic: 'F' } },
  { sourceTonic: 'Bb', step: 8, targetChroma: 6, expected: { status: 'ready', mode: 'minor', sourceTonic: 'Bb', targetTonic: 'F#' } },
  { sourceTonic: 'Bb', step: 9, targetChroma: 7, expected: { status: 'ready', mode: 'minor', sourceTonic: 'Bb', targetTonic: 'G' } },
  { sourceTonic: 'Bb', step: 10, targetChroma: 8, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'Bb', options: ['G#', 'Ab'] } },
  { sourceTonic: 'Bb', step: 11, targetChroma: 9, expected: { status: 'ready', mode: 'minor', sourceTonic: 'Bb', targetTonic: 'A' } },
  { sourceTonic: 'B', step: -11, targetChroma: 0, expected: { status: 'ready', mode: 'minor', sourceTonic: 'B', targetTonic: 'C' } },
  { sourceTonic: 'B', step: -10, targetChroma: 1, expected: { status: 'ready', mode: 'minor', sourceTonic: 'B', targetTonic: 'C#' } },
  { sourceTonic: 'B', step: -9, targetChroma: 2, expected: { status: 'ready', mode: 'minor', sourceTonic: 'B', targetTonic: 'D' } },
  { sourceTonic: 'B', step: -8, targetChroma: 3, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'B', options: ['D#', 'Eb'] } },
  { sourceTonic: 'B', step: -7, targetChroma: 4, expected: { status: 'ready', mode: 'minor', sourceTonic: 'B', targetTonic: 'E' } },
  { sourceTonic: 'B', step: -6, targetChroma: 5, expected: { status: 'ready', mode: 'minor', sourceTonic: 'B', targetTonic: 'F' } },
  { sourceTonic: 'B', step: -5, targetChroma: 6, expected: { status: 'ready', mode: 'minor', sourceTonic: 'B', targetTonic: 'F#' } },
  { sourceTonic: 'B', step: -4, targetChroma: 7, expected: { status: 'ready', mode: 'minor', sourceTonic: 'B', targetTonic: 'G' } },
  { sourceTonic: 'B', step: -3, targetChroma: 8, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'B', options: ['G#', 'Ab'] } },
  { sourceTonic: 'B', step: -2, targetChroma: 9, expected: { status: 'ready', mode: 'minor', sourceTonic: 'B', targetTonic: 'A' } },
  { sourceTonic: 'B', step: -1, targetChroma: 10, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'B', options: ['A#', 'Bb'] } },
  { sourceTonic: 'B', step: 0, targetChroma: 11, expected: { status: 'ready', mode: 'minor', sourceTonic: 'B', targetTonic: 'B' } },
  { sourceTonic: 'B', step: 1, targetChroma: 0, expected: { status: 'ready', mode: 'minor', sourceTonic: 'B', targetTonic: 'C' } },
  { sourceTonic: 'B', step: 2, targetChroma: 1, expected: { status: 'ready', mode: 'minor', sourceTonic: 'B', targetTonic: 'C#' } },
  { sourceTonic: 'B', step: 3, targetChroma: 2, expected: { status: 'ready', mode: 'minor', sourceTonic: 'B', targetTonic: 'D' } },
  { sourceTonic: 'B', step: 4, targetChroma: 3, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'B', options: ['D#', 'Eb'] } },
  { sourceTonic: 'B', step: 5, targetChroma: 4, expected: { status: 'ready', mode: 'minor', sourceTonic: 'B', targetTonic: 'E' } },
  { sourceTonic: 'B', step: 6, targetChroma: 5, expected: { status: 'ready', mode: 'minor', sourceTonic: 'B', targetTonic: 'F' } },
  { sourceTonic: 'B', step: 7, targetChroma: 6, expected: { status: 'ready', mode: 'minor', sourceTonic: 'B', targetTonic: 'F#' } },
  { sourceTonic: 'B', step: 8, targetChroma: 7, expected: { status: 'ready', mode: 'minor', sourceTonic: 'B', targetTonic: 'G' } },
  { sourceTonic: 'B', step: 9, targetChroma: 8, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'B', options: ['G#', 'Ab'] } },
  { sourceTonic: 'B', step: 10, targetChroma: 9, expected: { status: 'ready', mode: 'minor', sourceTonic: 'B', targetTonic: 'A' } },
  { sourceTonic: 'B', step: 11, targetChroma: 10, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'B', options: ['A#', 'Bb'] } },
];

