export interface MinorTranspositionMatrixRow {
  readonly sourceTonic: string;
  readonly step: number;
  readonly targetChroma: number;
  readonly expected:
    | {
        readonly status: 'ready';
        readonly mode: 'minor';
        readonly sourceTonic: string;
        readonly step: number;
        readonly targetTonic: string;
      }
    | {
        readonly status: 'requiresEnharmonicChoice';
        readonly mode: 'minor';
        readonly sourceTonic: string;
        readonly step: number;
        readonly options: readonly string[];
      };
}

/**
 * AC5:n eksplisiittinen tarkastusmatriisi:
 * 15 mollitoonikkaa x 23 sallittua askelta = 345 riviä.
 */
export const MINOR_TRANSPOSITION_MATRIX: readonly MinorTranspositionMatrixRow[] = [
  { sourceTonic: 'C', step: -11, targetChroma: 1, expected: { status: 'ready', mode: 'minor', sourceTonic: 'C', step: -11, targetTonic: 'C#' } },
  { sourceTonic: 'C', step: -10, targetChroma: 2, expected: { status: 'ready', mode: 'minor', sourceTonic: 'C', step: -10, targetTonic: 'D' } },
  { sourceTonic: 'C', step: -9, targetChroma: 3, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'C', step: -9, options: ['D#', 'Eb'] } },
  { sourceTonic: 'C', step: -8, targetChroma: 4, expected: { status: 'ready', mode: 'minor', sourceTonic: 'C', step: -8, targetTonic: 'E' } },
  { sourceTonic: 'C', step: -7, targetChroma: 5, expected: { status: 'ready', mode: 'minor', sourceTonic: 'C', step: -7, targetTonic: 'F' } },
  { sourceTonic: 'C', step: -6, targetChroma: 6, expected: { status: 'ready', mode: 'minor', sourceTonic: 'C', step: -6, targetTonic: 'F#' } },
  { sourceTonic: 'C', step: -5, targetChroma: 7, expected: { status: 'ready', mode: 'minor', sourceTonic: 'C', step: -5, targetTonic: 'G' } },
  { sourceTonic: 'C', step: -4, targetChroma: 8, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'C', step: -4, options: ['G#', 'Ab'] } },
  { sourceTonic: 'C', step: -3, targetChroma: 9, expected: { status: 'ready', mode: 'minor', sourceTonic: 'C', step: -3, targetTonic: 'A' } },
  { sourceTonic: 'C', step: -2, targetChroma: 10, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'C', step: -2, options: ['A#', 'Bb'] } },
  { sourceTonic: 'C', step: -1, targetChroma: 11, expected: { status: 'ready', mode: 'minor', sourceTonic: 'C', step: -1, targetTonic: 'B' } },
  { sourceTonic: 'C', step: 0, targetChroma: 0, expected: { status: 'ready', mode: 'minor', sourceTonic: 'C', step: 0, targetTonic: 'C' } },
  { sourceTonic: 'C', step: 1, targetChroma: 1, expected: { status: 'ready', mode: 'minor', sourceTonic: 'C', step: 1, targetTonic: 'C#' } },
  { sourceTonic: 'C', step: 2, targetChroma: 2, expected: { status: 'ready', mode: 'minor', sourceTonic: 'C', step: 2, targetTonic: 'D' } },
  { sourceTonic: 'C', step: 3, targetChroma: 3, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'C', step: 3, options: ['D#', 'Eb'] } },
  { sourceTonic: 'C', step: 4, targetChroma: 4, expected: { status: 'ready', mode: 'minor', sourceTonic: 'C', step: 4, targetTonic: 'E' } },
  { sourceTonic: 'C', step: 5, targetChroma: 5, expected: { status: 'ready', mode: 'minor', sourceTonic: 'C', step: 5, targetTonic: 'F' } },
  { sourceTonic: 'C', step: 6, targetChroma: 6, expected: { status: 'ready', mode: 'minor', sourceTonic: 'C', step: 6, targetTonic: 'F#' } },
  { sourceTonic: 'C', step: 7, targetChroma: 7, expected: { status: 'ready', mode: 'minor', sourceTonic: 'C', step: 7, targetTonic: 'G' } },
  { sourceTonic: 'C', step: 8, targetChroma: 8, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'C', step: 8, options: ['G#', 'Ab'] } },
  { sourceTonic: 'C', step: 9, targetChroma: 9, expected: { status: 'ready', mode: 'minor', sourceTonic: 'C', step: 9, targetTonic: 'A' } },
  { sourceTonic: 'C', step: 10, targetChroma: 10, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'C', step: 10, options: ['A#', 'Bb'] } },
  { sourceTonic: 'C', step: 11, targetChroma: 11, expected: { status: 'ready', mode: 'minor', sourceTonic: 'C', step: 11, targetTonic: 'B' } },
  { sourceTonic: 'C#', step: -11, targetChroma: 2, expected: { status: 'ready', mode: 'minor', sourceTonic: 'C#', step: -11, targetTonic: 'D' } },
  { sourceTonic: 'C#', step: -10, targetChroma: 3, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'C#', step: -10, options: ['D#', 'Eb'] } },
  { sourceTonic: 'C#', step: -9, targetChroma: 4, expected: { status: 'ready', mode: 'minor', sourceTonic: 'C#', step: -9, targetTonic: 'E' } },
  { sourceTonic: 'C#', step: -8, targetChroma: 5, expected: { status: 'ready', mode: 'minor', sourceTonic: 'C#', step: -8, targetTonic: 'F' } },
  { sourceTonic: 'C#', step: -7, targetChroma: 6, expected: { status: 'ready', mode: 'minor', sourceTonic: 'C#', step: -7, targetTonic: 'F#' } },
  { sourceTonic: 'C#', step: -6, targetChroma: 7, expected: { status: 'ready', mode: 'minor', sourceTonic: 'C#', step: -6, targetTonic: 'G' } },
  { sourceTonic: 'C#', step: -5, targetChroma: 8, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'C#', step: -5, options: ['G#', 'Ab'] } },
  { sourceTonic: 'C#', step: -4, targetChroma: 9, expected: { status: 'ready', mode: 'minor', sourceTonic: 'C#', step: -4, targetTonic: 'A' } },
  { sourceTonic: 'C#', step: -3, targetChroma: 10, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'C#', step: -3, options: ['A#', 'Bb'] } },
  { sourceTonic: 'C#', step: -2, targetChroma: 11, expected: { status: 'ready', mode: 'minor', sourceTonic: 'C#', step: -2, targetTonic: 'B' } },
  { sourceTonic: 'C#', step: -1, targetChroma: 0, expected: { status: 'ready', mode: 'minor', sourceTonic: 'C#', step: -1, targetTonic: 'C' } },
  { sourceTonic: 'C#', step: 0, targetChroma: 1, expected: { status: 'ready', mode: 'minor', sourceTonic: 'C#', step: 0, targetTonic: 'C#' } },
  { sourceTonic: 'C#', step: 1, targetChroma: 2, expected: { status: 'ready', mode: 'minor', sourceTonic: 'C#', step: 1, targetTonic: 'D' } },
  { sourceTonic: 'C#', step: 2, targetChroma: 3, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'C#', step: 2, options: ['D#', 'Eb'] } },
  { sourceTonic: 'C#', step: 3, targetChroma: 4, expected: { status: 'ready', mode: 'minor', sourceTonic: 'C#', step: 3, targetTonic: 'E' } },
  { sourceTonic: 'C#', step: 4, targetChroma: 5, expected: { status: 'ready', mode: 'minor', sourceTonic: 'C#', step: 4, targetTonic: 'F' } },
  { sourceTonic: 'C#', step: 5, targetChroma: 6, expected: { status: 'ready', mode: 'minor', sourceTonic: 'C#', step: 5, targetTonic: 'F#' } },
  { sourceTonic: 'C#', step: 6, targetChroma: 7, expected: { status: 'ready', mode: 'minor', sourceTonic: 'C#', step: 6, targetTonic: 'G' } },
  { sourceTonic: 'C#', step: 7, targetChroma: 8, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'C#', step: 7, options: ['G#', 'Ab'] } },
  { sourceTonic: 'C#', step: 8, targetChroma: 9, expected: { status: 'ready', mode: 'minor', sourceTonic: 'C#', step: 8, targetTonic: 'A' } },
  { sourceTonic: 'C#', step: 9, targetChroma: 10, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'C#', step: 9, options: ['A#', 'Bb'] } },
  { sourceTonic: 'C#', step: 10, targetChroma: 11, expected: { status: 'ready', mode: 'minor', sourceTonic: 'C#', step: 10, targetTonic: 'B' } },
  { sourceTonic: 'C#', step: 11, targetChroma: 0, expected: { status: 'ready', mode: 'minor', sourceTonic: 'C#', step: 11, targetTonic: 'C' } },
  { sourceTonic: 'D', step: -11, targetChroma: 3, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'D', step: -11, options: ['D#', 'Eb'] } },
  { sourceTonic: 'D', step: -10, targetChroma: 4, expected: { status: 'ready', mode: 'minor', sourceTonic: 'D', step: -10, targetTonic: 'E' } },
  { sourceTonic: 'D', step: -9, targetChroma: 5, expected: { status: 'ready', mode: 'minor', sourceTonic: 'D', step: -9, targetTonic: 'F' } },
  { sourceTonic: 'D', step: -8, targetChroma: 6, expected: { status: 'ready', mode: 'minor', sourceTonic: 'D', step: -8, targetTonic: 'F#' } },
  { sourceTonic: 'D', step: -7, targetChroma: 7, expected: { status: 'ready', mode: 'minor', sourceTonic: 'D', step: -7, targetTonic: 'G' } },
  { sourceTonic: 'D', step: -6, targetChroma: 8, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'D', step: -6, options: ['G#', 'Ab'] } },
  { sourceTonic: 'D', step: -5, targetChroma: 9, expected: { status: 'ready', mode: 'minor', sourceTonic: 'D', step: -5, targetTonic: 'A' } },
  { sourceTonic: 'D', step: -4, targetChroma: 10, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'D', step: -4, options: ['A#', 'Bb'] } },
  { sourceTonic: 'D', step: -3, targetChroma: 11, expected: { status: 'ready', mode: 'minor', sourceTonic: 'D', step: -3, targetTonic: 'B' } },
  { sourceTonic: 'D', step: -2, targetChroma: 0, expected: { status: 'ready', mode: 'minor', sourceTonic: 'D', step: -2, targetTonic: 'C' } },
  { sourceTonic: 'D', step: -1, targetChroma: 1, expected: { status: 'ready', mode: 'minor', sourceTonic: 'D', step: -1, targetTonic: 'C#' } },
  { sourceTonic: 'D', step: 0, targetChroma: 2, expected: { status: 'ready', mode: 'minor', sourceTonic: 'D', step: 0, targetTonic: 'D' } },
  { sourceTonic: 'D', step: 1, targetChroma: 3, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'D', step: 1, options: ['D#', 'Eb'] } },
  { sourceTonic: 'D', step: 2, targetChroma: 4, expected: { status: 'ready', mode: 'minor', sourceTonic: 'D', step: 2, targetTonic: 'E' } },
  { sourceTonic: 'D', step: 3, targetChroma: 5, expected: { status: 'ready', mode: 'minor', sourceTonic: 'D', step: 3, targetTonic: 'F' } },
  { sourceTonic: 'D', step: 4, targetChroma: 6, expected: { status: 'ready', mode: 'minor', sourceTonic: 'D', step: 4, targetTonic: 'F#' } },
  { sourceTonic: 'D', step: 5, targetChroma: 7, expected: { status: 'ready', mode: 'minor', sourceTonic: 'D', step: 5, targetTonic: 'G' } },
  { sourceTonic: 'D', step: 6, targetChroma: 8, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'D', step: 6, options: ['G#', 'Ab'] } },
  { sourceTonic: 'D', step: 7, targetChroma: 9, expected: { status: 'ready', mode: 'minor', sourceTonic: 'D', step: 7, targetTonic: 'A' } },
  { sourceTonic: 'D', step: 8, targetChroma: 10, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'D', step: 8, options: ['A#', 'Bb'] } },
  { sourceTonic: 'D', step: 9, targetChroma: 11, expected: { status: 'ready', mode: 'minor', sourceTonic: 'D', step: 9, targetTonic: 'B' } },
  { sourceTonic: 'D', step: 10, targetChroma: 0, expected: { status: 'ready', mode: 'minor', sourceTonic: 'D', step: 10, targetTonic: 'C' } },
  { sourceTonic: 'D', step: 11, targetChroma: 1, expected: { status: 'ready', mode: 'minor', sourceTonic: 'D', step: 11, targetTonic: 'C#' } },
  { sourceTonic: 'D#', step: -11, targetChroma: 4, expected: { status: 'ready', mode: 'minor', sourceTonic: 'D#', step: -11, targetTonic: 'E' } },
  { sourceTonic: 'D#', step: -10, targetChroma: 5, expected: { status: 'ready', mode: 'minor', sourceTonic: 'D#', step: -10, targetTonic: 'F' } },
  { sourceTonic: 'D#', step: -9, targetChroma: 6, expected: { status: 'ready', mode: 'minor', sourceTonic: 'D#', step: -9, targetTonic: 'F#' } },
  { sourceTonic: 'D#', step: -8, targetChroma: 7, expected: { status: 'ready', mode: 'minor', sourceTonic: 'D#', step: -8, targetTonic: 'G' } },
  { sourceTonic: 'D#', step: -7, targetChroma: 8, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'D#', step: -7, options: ['G#', 'Ab'] } },
  { sourceTonic: 'D#', step: -6, targetChroma: 9, expected: { status: 'ready', mode: 'minor', sourceTonic: 'D#', step: -6, targetTonic: 'A' } },
  { sourceTonic: 'D#', step: -5, targetChroma: 10, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'D#', step: -5, options: ['A#', 'Bb'] } },
  { sourceTonic: 'D#', step: -4, targetChroma: 11, expected: { status: 'ready', mode: 'minor', sourceTonic: 'D#', step: -4, targetTonic: 'B' } },
  { sourceTonic: 'D#', step: -3, targetChroma: 0, expected: { status: 'ready', mode: 'minor', sourceTonic: 'D#', step: -3, targetTonic: 'C' } },
  { sourceTonic: 'D#', step: -2, targetChroma: 1, expected: { status: 'ready', mode: 'minor', sourceTonic: 'D#', step: -2, targetTonic: 'C#' } },
  { sourceTonic: 'D#', step: -1, targetChroma: 2, expected: { status: 'ready', mode: 'minor', sourceTonic: 'D#', step: -1, targetTonic: 'D' } },
  { sourceTonic: 'D#', step: 0, targetChroma: 3, expected: { status: 'ready', mode: 'minor', sourceTonic: 'D#', step: 0, targetTonic: 'D#' } },
  { sourceTonic: 'D#', step: 1, targetChroma: 4, expected: { status: 'ready', mode: 'minor', sourceTonic: 'D#', step: 1, targetTonic: 'E' } },
  { sourceTonic: 'D#', step: 2, targetChroma: 5, expected: { status: 'ready', mode: 'minor', sourceTonic: 'D#', step: 2, targetTonic: 'F' } },
  { sourceTonic: 'D#', step: 3, targetChroma: 6, expected: { status: 'ready', mode: 'minor', sourceTonic: 'D#', step: 3, targetTonic: 'F#' } },
  { sourceTonic: 'D#', step: 4, targetChroma: 7, expected: { status: 'ready', mode: 'minor', sourceTonic: 'D#', step: 4, targetTonic: 'G' } },
  { sourceTonic: 'D#', step: 5, targetChroma: 8, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'D#', step: 5, options: ['G#', 'Ab'] } },
  { sourceTonic: 'D#', step: 6, targetChroma: 9, expected: { status: 'ready', mode: 'minor', sourceTonic: 'D#', step: 6, targetTonic: 'A' } },
  { sourceTonic: 'D#', step: 7, targetChroma: 10, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'D#', step: 7, options: ['A#', 'Bb'] } },
  { sourceTonic: 'D#', step: 8, targetChroma: 11, expected: { status: 'ready', mode: 'minor', sourceTonic: 'D#', step: 8, targetTonic: 'B' } },
  { sourceTonic: 'D#', step: 9, targetChroma: 0, expected: { status: 'ready', mode: 'minor', sourceTonic: 'D#', step: 9, targetTonic: 'C' } },
  { sourceTonic: 'D#', step: 10, targetChroma: 1, expected: { status: 'ready', mode: 'minor', sourceTonic: 'D#', step: 10, targetTonic: 'C#' } },
  { sourceTonic: 'D#', step: 11, targetChroma: 2, expected: { status: 'ready', mode: 'minor', sourceTonic: 'D#', step: 11, targetTonic: 'D' } },
  { sourceTonic: 'Eb', step: -11, targetChroma: 4, expected: { status: 'ready', mode: 'minor', sourceTonic: 'Eb', step: -11, targetTonic: 'E' } },
  { sourceTonic: 'Eb', step: -10, targetChroma: 5, expected: { status: 'ready', mode: 'minor', sourceTonic: 'Eb', step: -10, targetTonic: 'F' } },
  { sourceTonic: 'Eb', step: -9, targetChroma: 6, expected: { status: 'ready', mode: 'minor', sourceTonic: 'Eb', step: -9, targetTonic: 'F#' } },
  { sourceTonic: 'Eb', step: -8, targetChroma: 7, expected: { status: 'ready', mode: 'minor', sourceTonic: 'Eb', step: -8, targetTonic: 'G' } },
  { sourceTonic: 'Eb', step: -7, targetChroma: 8, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'Eb', step: -7, options: ['G#', 'Ab'] } },
  { sourceTonic: 'Eb', step: -6, targetChroma: 9, expected: { status: 'ready', mode: 'minor', sourceTonic: 'Eb', step: -6, targetTonic: 'A' } },
  { sourceTonic: 'Eb', step: -5, targetChroma: 10, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'Eb', step: -5, options: ['A#', 'Bb'] } },
  { sourceTonic: 'Eb', step: -4, targetChroma: 11, expected: { status: 'ready', mode: 'minor', sourceTonic: 'Eb', step: -4, targetTonic: 'B' } },
  { sourceTonic: 'Eb', step: -3, targetChroma: 0, expected: { status: 'ready', mode: 'minor', sourceTonic: 'Eb', step: -3, targetTonic: 'C' } },
  { sourceTonic: 'Eb', step: -2, targetChroma: 1, expected: { status: 'ready', mode: 'minor', sourceTonic: 'Eb', step: -2, targetTonic: 'C#' } },
  { sourceTonic: 'Eb', step: -1, targetChroma: 2, expected: { status: 'ready', mode: 'minor', sourceTonic: 'Eb', step: -1, targetTonic: 'D' } },
  { sourceTonic: 'Eb', step: 0, targetChroma: 3, expected: { status: 'ready', mode: 'minor', sourceTonic: 'Eb', step: 0, targetTonic: 'Eb' } },
  { sourceTonic: 'Eb', step: 1, targetChroma: 4, expected: { status: 'ready', mode: 'minor', sourceTonic: 'Eb', step: 1, targetTonic: 'E' } },
  { sourceTonic: 'Eb', step: 2, targetChroma: 5, expected: { status: 'ready', mode: 'minor', sourceTonic: 'Eb', step: 2, targetTonic: 'F' } },
  { sourceTonic: 'Eb', step: 3, targetChroma: 6, expected: { status: 'ready', mode: 'minor', sourceTonic: 'Eb', step: 3, targetTonic: 'F#' } },
  { sourceTonic: 'Eb', step: 4, targetChroma: 7, expected: { status: 'ready', mode: 'minor', sourceTonic: 'Eb', step: 4, targetTonic: 'G' } },
  { sourceTonic: 'Eb', step: 5, targetChroma: 8, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'Eb', step: 5, options: ['G#', 'Ab'] } },
  { sourceTonic: 'Eb', step: 6, targetChroma: 9, expected: { status: 'ready', mode: 'minor', sourceTonic: 'Eb', step: 6, targetTonic: 'A' } },
  { sourceTonic: 'Eb', step: 7, targetChroma: 10, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'Eb', step: 7, options: ['A#', 'Bb'] } },
  { sourceTonic: 'Eb', step: 8, targetChroma: 11, expected: { status: 'ready', mode: 'minor', sourceTonic: 'Eb', step: 8, targetTonic: 'B' } },
  { sourceTonic: 'Eb', step: 9, targetChroma: 0, expected: { status: 'ready', mode: 'minor', sourceTonic: 'Eb', step: 9, targetTonic: 'C' } },
  { sourceTonic: 'Eb', step: 10, targetChroma: 1, expected: { status: 'ready', mode: 'minor', sourceTonic: 'Eb', step: 10, targetTonic: 'C#' } },
  { sourceTonic: 'Eb', step: 11, targetChroma: 2, expected: { status: 'ready', mode: 'minor', sourceTonic: 'Eb', step: 11, targetTonic: 'D' } },
  { sourceTonic: 'E', step: -11, targetChroma: 5, expected: { status: 'ready', mode: 'minor', sourceTonic: 'E', step: -11, targetTonic: 'F' } },
  { sourceTonic: 'E', step: -10, targetChroma: 6, expected: { status: 'ready', mode: 'minor', sourceTonic: 'E', step: -10, targetTonic: 'F#' } },
  { sourceTonic: 'E', step: -9, targetChroma: 7, expected: { status: 'ready', mode: 'minor', sourceTonic: 'E', step: -9, targetTonic: 'G' } },
  { sourceTonic: 'E', step: -8, targetChroma: 8, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'E', step: -8, options: ['G#', 'Ab'] } },
  { sourceTonic: 'E', step: -7, targetChroma: 9, expected: { status: 'ready', mode: 'minor', sourceTonic: 'E', step: -7, targetTonic: 'A' } },
  { sourceTonic: 'E', step: -6, targetChroma: 10, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'E', step: -6, options: ['A#', 'Bb'] } },
  { sourceTonic: 'E', step: -5, targetChroma: 11, expected: { status: 'ready', mode: 'minor', sourceTonic: 'E', step: -5, targetTonic: 'B' } },
  { sourceTonic: 'E', step: -4, targetChroma: 0, expected: { status: 'ready', mode: 'minor', sourceTonic: 'E', step: -4, targetTonic: 'C' } },
  { sourceTonic: 'E', step: -3, targetChroma: 1, expected: { status: 'ready', mode: 'minor', sourceTonic: 'E', step: -3, targetTonic: 'C#' } },
  { sourceTonic: 'E', step: -2, targetChroma: 2, expected: { status: 'ready', mode: 'minor', sourceTonic: 'E', step: -2, targetTonic: 'D' } },
  { sourceTonic: 'E', step: -1, targetChroma: 3, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'E', step: -1, options: ['D#', 'Eb'] } },
  { sourceTonic: 'E', step: 0, targetChroma: 4, expected: { status: 'ready', mode: 'minor', sourceTonic: 'E', step: 0, targetTonic: 'E' } },
  { sourceTonic: 'E', step: 1, targetChroma: 5, expected: { status: 'ready', mode: 'minor', sourceTonic: 'E', step: 1, targetTonic: 'F' } },
  { sourceTonic: 'E', step: 2, targetChroma: 6, expected: { status: 'ready', mode: 'minor', sourceTonic: 'E', step: 2, targetTonic: 'F#' } },
  { sourceTonic: 'E', step: 3, targetChroma: 7, expected: { status: 'ready', mode: 'minor', sourceTonic: 'E', step: 3, targetTonic: 'G' } },
  { sourceTonic: 'E', step: 4, targetChroma: 8, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'E', step: 4, options: ['G#', 'Ab'] } },
  { sourceTonic: 'E', step: 5, targetChroma: 9, expected: { status: 'ready', mode: 'minor', sourceTonic: 'E', step: 5, targetTonic: 'A' } },
  { sourceTonic: 'E', step: 6, targetChroma: 10, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'E', step: 6, options: ['A#', 'Bb'] } },
  { sourceTonic: 'E', step: 7, targetChroma: 11, expected: { status: 'ready', mode: 'minor', sourceTonic: 'E', step: 7, targetTonic: 'B' } },
  { sourceTonic: 'E', step: 8, targetChroma: 0, expected: { status: 'ready', mode: 'minor', sourceTonic: 'E', step: 8, targetTonic: 'C' } },
  { sourceTonic: 'E', step: 9, targetChroma: 1, expected: { status: 'ready', mode: 'minor', sourceTonic: 'E', step: 9, targetTonic: 'C#' } },
  { sourceTonic: 'E', step: 10, targetChroma: 2, expected: { status: 'ready', mode: 'minor', sourceTonic: 'E', step: 10, targetTonic: 'D' } },
  { sourceTonic: 'E', step: 11, targetChroma: 3, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'E', step: 11, options: ['D#', 'Eb'] } },
  { sourceTonic: 'F', step: -11, targetChroma: 6, expected: { status: 'ready', mode: 'minor', sourceTonic: 'F', step: -11, targetTonic: 'F#' } },
  { sourceTonic: 'F', step: -10, targetChroma: 7, expected: { status: 'ready', mode: 'minor', sourceTonic: 'F', step: -10, targetTonic: 'G' } },
  { sourceTonic: 'F', step: -9, targetChroma: 8, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'F', step: -9, options: ['G#', 'Ab'] } },
  { sourceTonic: 'F', step: -8, targetChroma: 9, expected: { status: 'ready', mode: 'minor', sourceTonic: 'F', step: -8, targetTonic: 'A' } },
  { sourceTonic: 'F', step: -7, targetChroma: 10, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'F', step: -7, options: ['A#', 'Bb'] } },
  { sourceTonic: 'F', step: -6, targetChroma: 11, expected: { status: 'ready', mode: 'minor', sourceTonic: 'F', step: -6, targetTonic: 'B' } },
  { sourceTonic: 'F', step: -5, targetChroma: 0, expected: { status: 'ready', mode: 'minor', sourceTonic: 'F', step: -5, targetTonic: 'C' } },
  { sourceTonic: 'F', step: -4, targetChroma: 1, expected: { status: 'ready', mode: 'minor', sourceTonic: 'F', step: -4, targetTonic: 'C#' } },
  { sourceTonic: 'F', step: -3, targetChroma: 2, expected: { status: 'ready', mode: 'minor', sourceTonic: 'F', step: -3, targetTonic: 'D' } },
  { sourceTonic: 'F', step: -2, targetChroma: 3, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'F', step: -2, options: ['D#', 'Eb'] } },
  { sourceTonic: 'F', step: -1, targetChroma: 4, expected: { status: 'ready', mode: 'minor', sourceTonic: 'F', step: -1, targetTonic: 'E' } },
  { sourceTonic: 'F', step: 0, targetChroma: 5, expected: { status: 'ready', mode: 'minor', sourceTonic: 'F', step: 0, targetTonic: 'F' } },
  { sourceTonic: 'F', step: 1, targetChroma: 6, expected: { status: 'ready', mode: 'minor', sourceTonic: 'F', step: 1, targetTonic: 'F#' } },
  { sourceTonic: 'F', step: 2, targetChroma: 7, expected: { status: 'ready', mode: 'minor', sourceTonic: 'F', step: 2, targetTonic: 'G' } },
  { sourceTonic: 'F', step: 3, targetChroma: 8, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'F', step: 3, options: ['G#', 'Ab'] } },
  { sourceTonic: 'F', step: 4, targetChroma: 9, expected: { status: 'ready', mode: 'minor', sourceTonic: 'F', step: 4, targetTonic: 'A' } },
  { sourceTonic: 'F', step: 5, targetChroma: 10, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'F', step: 5, options: ['A#', 'Bb'] } },
  { sourceTonic: 'F', step: 6, targetChroma: 11, expected: { status: 'ready', mode: 'minor', sourceTonic: 'F', step: 6, targetTonic: 'B' } },
  { sourceTonic: 'F', step: 7, targetChroma: 0, expected: { status: 'ready', mode: 'minor', sourceTonic: 'F', step: 7, targetTonic: 'C' } },
  { sourceTonic: 'F', step: 8, targetChroma: 1, expected: { status: 'ready', mode: 'minor', sourceTonic: 'F', step: 8, targetTonic: 'C#' } },
  { sourceTonic: 'F', step: 9, targetChroma: 2, expected: { status: 'ready', mode: 'minor', sourceTonic: 'F', step: 9, targetTonic: 'D' } },
  { sourceTonic: 'F', step: 10, targetChroma: 3, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'F', step: 10, options: ['D#', 'Eb'] } },
  { sourceTonic: 'F', step: 11, targetChroma: 4, expected: { status: 'ready', mode: 'minor', sourceTonic: 'F', step: 11, targetTonic: 'E' } },
  { sourceTonic: 'F#', step: -11, targetChroma: 7, expected: { status: 'ready', mode: 'minor', sourceTonic: 'F#', step: -11, targetTonic: 'G' } },
  { sourceTonic: 'F#', step: -10, targetChroma: 8, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'F#', step: -10, options: ['G#', 'Ab'] } },
  { sourceTonic: 'F#', step: -9, targetChroma: 9, expected: { status: 'ready', mode: 'minor', sourceTonic: 'F#', step: -9, targetTonic: 'A' } },
  { sourceTonic: 'F#', step: -8, targetChroma: 10, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'F#', step: -8, options: ['A#', 'Bb'] } },
  { sourceTonic: 'F#', step: -7, targetChroma: 11, expected: { status: 'ready', mode: 'minor', sourceTonic: 'F#', step: -7, targetTonic: 'B' } },
  { sourceTonic: 'F#', step: -6, targetChroma: 0, expected: { status: 'ready', mode: 'minor', sourceTonic: 'F#', step: -6, targetTonic: 'C' } },
  { sourceTonic: 'F#', step: -5, targetChroma: 1, expected: { status: 'ready', mode: 'minor', sourceTonic: 'F#', step: -5, targetTonic: 'C#' } },
  { sourceTonic: 'F#', step: -4, targetChroma: 2, expected: { status: 'ready', mode: 'minor', sourceTonic: 'F#', step: -4, targetTonic: 'D' } },
  { sourceTonic: 'F#', step: -3, targetChroma: 3, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'F#', step: -3, options: ['D#', 'Eb'] } },
  { sourceTonic: 'F#', step: -2, targetChroma: 4, expected: { status: 'ready', mode: 'minor', sourceTonic: 'F#', step: -2, targetTonic: 'E' } },
  { sourceTonic: 'F#', step: -1, targetChroma: 5, expected: { status: 'ready', mode: 'minor', sourceTonic: 'F#', step: -1, targetTonic: 'F' } },
  { sourceTonic: 'F#', step: 0, targetChroma: 6, expected: { status: 'ready', mode: 'minor', sourceTonic: 'F#', step: 0, targetTonic: 'F#' } },
  { sourceTonic: 'F#', step: 1, targetChroma: 7, expected: { status: 'ready', mode: 'minor', sourceTonic: 'F#', step: 1, targetTonic: 'G' } },
  { sourceTonic: 'F#', step: 2, targetChroma: 8, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'F#', step: 2, options: ['G#', 'Ab'] } },
  { sourceTonic: 'F#', step: 3, targetChroma: 9, expected: { status: 'ready', mode: 'minor', sourceTonic: 'F#', step: 3, targetTonic: 'A' } },
  { sourceTonic: 'F#', step: 4, targetChroma: 10, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'F#', step: 4, options: ['A#', 'Bb'] } },
  { sourceTonic: 'F#', step: 5, targetChroma: 11, expected: { status: 'ready', mode: 'minor', sourceTonic: 'F#', step: 5, targetTonic: 'B' } },
  { sourceTonic: 'F#', step: 6, targetChroma: 0, expected: { status: 'ready', mode: 'minor', sourceTonic: 'F#', step: 6, targetTonic: 'C' } },
  { sourceTonic: 'F#', step: 7, targetChroma: 1, expected: { status: 'ready', mode: 'minor', sourceTonic: 'F#', step: 7, targetTonic: 'C#' } },
  { sourceTonic: 'F#', step: 8, targetChroma: 2, expected: { status: 'ready', mode: 'minor', sourceTonic: 'F#', step: 8, targetTonic: 'D' } },
  { sourceTonic: 'F#', step: 9, targetChroma: 3, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'F#', step: 9, options: ['D#', 'Eb'] } },
  { sourceTonic: 'F#', step: 10, targetChroma: 4, expected: { status: 'ready', mode: 'minor', sourceTonic: 'F#', step: 10, targetTonic: 'E' } },
  { sourceTonic: 'F#', step: 11, targetChroma: 5, expected: { status: 'ready', mode: 'minor', sourceTonic: 'F#', step: 11, targetTonic: 'F' } },
  { sourceTonic: 'G', step: -11, targetChroma: 8, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'G', step: -11, options: ['G#', 'Ab'] } },
  { sourceTonic: 'G', step: -10, targetChroma: 9, expected: { status: 'ready', mode: 'minor', sourceTonic: 'G', step: -10, targetTonic: 'A' } },
  { sourceTonic: 'G', step: -9, targetChroma: 10, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'G', step: -9, options: ['A#', 'Bb'] } },
  { sourceTonic: 'G', step: -8, targetChroma: 11, expected: { status: 'ready', mode: 'minor', sourceTonic: 'G', step: -8, targetTonic: 'B' } },
  { sourceTonic: 'G', step: -7, targetChroma: 0, expected: { status: 'ready', mode: 'minor', sourceTonic: 'G', step: -7, targetTonic: 'C' } },
  { sourceTonic: 'G', step: -6, targetChroma: 1, expected: { status: 'ready', mode: 'minor', sourceTonic: 'G', step: -6, targetTonic: 'C#' } },
  { sourceTonic: 'G', step: -5, targetChroma: 2, expected: { status: 'ready', mode: 'minor', sourceTonic: 'G', step: -5, targetTonic: 'D' } },
  { sourceTonic: 'G', step: -4, targetChroma: 3, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'G', step: -4, options: ['D#', 'Eb'] } },
  { sourceTonic: 'G', step: -3, targetChroma: 4, expected: { status: 'ready', mode: 'minor', sourceTonic: 'G', step: -3, targetTonic: 'E' } },
  { sourceTonic: 'G', step: -2, targetChroma: 5, expected: { status: 'ready', mode: 'minor', sourceTonic: 'G', step: -2, targetTonic: 'F' } },
  { sourceTonic: 'G', step: -1, targetChroma: 6, expected: { status: 'ready', mode: 'minor', sourceTonic: 'G', step: -1, targetTonic: 'F#' } },
  { sourceTonic: 'G', step: 0, targetChroma: 7, expected: { status: 'ready', mode: 'minor', sourceTonic: 'G', step: 0, targetTonic: 'G' } },
  { sourceTonic: 'G', step: 1, targetChroma: 8, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'G', step: 1, options: ['G#', 'Ab'] } },
  { sourceTonic: 'G', step: 2, targetChroma: 9, expected: { status: 'ready', mode: 'minor', sourceTonic: 'G', step: 2, targetTonic: 'A' } },
  { sourceTonic: 'G', step: 3, targetChroma: 10, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'G', step: 3, options: ['A#', 'Bb'] } },
  { sourceTonic: 'G', step: 4, targetChroma: 11, expected: { status: 'ready', mode: 'minor', sourceTonic: 'G', step: 4, targetTonic: 'B' } },
  { sourceTonic: 'G', step: 5, targetChroma: 0, expected: { status: 'ready', mode: 'minor', sourceTonic: 'G', step: 5, targetTonic: 'C' } },
  { sourceTonic: 'G', step: 6, targetChroma: 1, expected: { status: 'ready', mode: 'minor', sourceTonic: 'G', step: 6, targetTonic: 'C#' } },
  { sourceTonic: 'G', step: 7, targetChroma: 2, expected: { status: 'ready', mode: 'minor', sourceTonic: 'G', step: 7, targetTonic: 'D' } },
  { sourceTonic: 'G', step: 8, targetChroma: 3, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'G', step: 8, options: ['D#', 'Eb'] } },
  { sourceTonic: 'G', step: 9, targetChroma: 4, expected: { status: 'ready', mode: 'minor', sourceTonic: 'G', step: 9, targetTonic: 'E' } },
  { sourceTonic: 'G', step: 10, targetChroma: 5, expected: { status: 'ready', mode: 'minor', sourceTonic: 'G', step: 10, targetTonic: 'F' } },
  { sourceTonic: 'G', step: 11, targetChroma: 6, expected: { status: 'ready', mode: 'minor', sourceTonic: 'G', step: 11, targetTonic: 'F#' } },
  { sourceTonic: 'G#', step: -11, targetChroma: 9, expected: { status: 'ready', mode: 'minor', sourceTonic: 'G#', step: -11, targetTonic: 'A' } },
  { sourceTonic: 'G#', step: -10, targetChroma: 10, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'G#', step: -10, options: ['A#', 'Bb'] } },
  { sourceTonic: 'G#', step: -9, targetChroma: 11, expected: { status: 'ready', mode: 'minor', sourceTonic: 'G#', step: -9, targetTonic: 'B' } },
  { sourceTonic: 'G#', step: -8, targetChroma: 0, expected: { status: 'ready', mode: 'minor', sourceTonic: 'G#', step: -8, targetTonic: 'C' } },
  { sourceTonic: 'G#', step: -7, targetChroma: 1, expected: { status: 'ready', mode: 'minor', sourceTonic: 'G#', step: -7, targetTonic: 'C#' } },
  { sourceTonic: 'G#', step: -6, targetChroma: 2, expected: { status: 'ready', mode: 'minor', sourceTonic: 'G#', step: -6, targetTonic: 'D' } },
  { sourceTonic: 'G#', step: -5, targetChroma: 3, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'G#', step: -5, options: ['D#', 'Eb'] } },
  { sourceTonic: 'G#', step: -4, targetChroma: 4, expected: { status: 'ready', mode: 'minor', sourceTonic: 'G#', step: -4, targetTonic: 'E' } },
  { sourceTonic: 'G#', step: -3, targetChroma: 5, expected: { status: 'ready', mode: 'minor', sourceTonic: 'G#', step: -3, targetTonic: 'F' } },
  { sourceTonic: 'G#', step: -2, targetChroma: 6, expected: { status: 'ready', mode: 'minor', sourceTonic: 'G#', step: -2, targetTonic: 'F#' } },
  { sourceTonic: 'G#', step: -1, targetChroma: 7, expected: { status: 'ready', mode: 'minor', sourceTonic: 'G#', step: -1, targetTonic: 'G' } },
  { sourceTonic: 'G#', step: 0, targetChroma: 8, expected: { status: 'ready', mode: 'minor', sourceTonic: 'G#', step: 0, targetTonic: 'G#' } },
  { sourceTonic: 'G#', step: 1, targetChroma: 9, expected: { status: 'ready', mode: 'minor', sourceTonic: 'G#', step: 1, targetTonic: 'A' } },
  { sourceTonic: 'G#', step: 2, targetChroma: 10, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'G#', step: 2, options: ['A#', 'Bb'] } },
  { sourceTonic: 'G#', step: 3, targetChroma: 11, expected: { status: 'ready', mode: 'minor', sourceTonic: 'G#', step: 3, targetTonic: 'B' } },
  { sourceTonic: 'G#', step: 4, targetChroma: 0, expected: { status: 'ready', mode: 'minor', sourceTonic: 'G#', step: 4, targetTonic: 'C' } },
  { sourceTonic: 'G#', step: 5, targetChroma: 1, expected: { status: 'ready', mode: 'minor', sourceTonic: 'G#', step: 5, targetTonic: 'C#' } },
  { sourceTonic: 'G#', step: 6, targetChroma: 2, expected: { status: 'ready', mode: 'minor', sourceTonic: 'G#', step: 6, targetTonic: 'D' } },
  { sourceTonic: 'G#', step: 7, targetChroma: 3, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'G#', step: 7, options: ['D#', 'Eb'] } },
  { sourceTonic: 'G#', step: 8, targetChroma: 4, expected: { status: 'ready', mode: 'minor', sourceTonic: 'G#', step: 8, targetTonic: 'E' } },
  { sourceTonic: 'G#', step: 9, targetChroma: 5, expected: { status: 'ready', mode: 'minor', sourceTonic: 'G#', step: 9, targetTonic: 'F' } },
  { sourceTonic: 'G#', step: 10, targetChroma: 6, expected: { status: 'ready', mode: 'minor', sourceTonic: 'G#', step: 10, targetTonic: 'F#' } },
  { sourceTonic: 'G#', step: 11, targetChroma: 7, expected: { status: 'ready', mode: 'minor', sourceTonic: 'G#', step: 11, targetTonic: 'G' } },
  { sourceTonic: 'Ab', step: -11, targetChroma: 9, expected: { status: 'ready', mode: 'minor', sourceTonic: 'Ab', step: -11, targetTonic: 'A' } },
  { sourceTonic: 'Ab', step: -10, targetChroma: 10, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'Ab', step: -10, options: ['A#', 'Bb'] } },
  { sourceTonic: 'Ab', step: -9, targetChroma: 11, expected: { status: 'ready', mode: 'minor', sourceTonic: 'Ab', step: -9, targetTonic: 'B' } },
  { sourceTonic: 'Ab', step: -8, targetChroma: 0, expected: { status: 'ready', mode: 'minor', sourceTonic: 'Ab', step: -8, targetTonic: 'C' } },
  { sourceTonic: 'Ab', step: -7, targetChroma: 1, expected: { status: 'ready', mode: 'minor', sourceTonic: 'Ab', step: -7, targetTonic: 'C#' } },
  { sourceTonic: 'Ab', step: -6, targetChroma: 2, expected: { status: 'ready', mode: 'minor', sourceTonic: 'Ab', step: -6, targetTonic: 'D' } },
  { sourceTonic: 'Ab', step: -5, targetChroma: 3, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'Ab', step: -5, options: ['D#', 'Eb'] } },
  { sourceTonic: 'Ab', step: -4, targetChroma: 4, expected: { status: 'ready', mode: 'minor', sourceTonic: 'Ab', step: -4, targetTonic: 'E' } },
  { sourceTonic: 'Ab', step: -3, targetChroma: 5, expected: { status: 'ready', mode: 'minor', sourceTonic: 'Ab', step: -3, targetTonic: 'F' } },
  { sourceTonic: 'Ab', step: -2, targetChroma: 6, expected: { status: 'ready', mode: 'minor', sourceTonic: 'Ab', step: -2, targetTonic: 'F#' } },
  { sourceTonic: 'Ab', step: -1, targetChroma: 7, expected: { status: 'ready', mode: 'minor', sourceTonic: 'Ab', step: -1, targetTonic: 'G' } },
  { sourceTonic: 'Ab', step: 0, targetChroma: 8, expected: { status: 'ready', mode: 'minor', sourceTonic: 'Ab', step: 0, targetTonic: 'Ab' } },
  { sourceTonic: 'Ab', step: 1, targetChroma: 9, expected: { status: 'ready', mode: 'minor', sourceTonic: 'Ab', step: 1, targetTonic: 'A' } },
  { sourceTonic: 'Ab', step: 2, targetChroma: 10, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'Ab', step: 2, options: ['A#', 'Bb'] } },
  { sourceTonic: 'Ab', step: 3, targetChroma: 11, expected: { status: 'ready', mode: 'minor', sourceTonic: 'Ab', step: 3, targetTonic: 'B' } },
  { sourceTonic: 'Ab', step: 4, targetChroma: 0, expected: { status: 'ready', mode: 'minor', sourceTonic: 'Ab', step: 4, targetTonic: 'C' } },
  { sourceTonic: 'Ab', step: 5, targetChroma: 1, expected: { status: 'ready', mode: 'minor', sourceTonic: 'Ab', step: 5, targetTonic: 'C#' } },
  { sourceTonic: 'Ab', step: 6, targetChroma: 2, expected: { status: 'ready', mode: 'minor', sourceTonic: 'Ab', step: 6, targetTonic: 'D' } },
  { sourceTonic: 'Ab', step: 7, targetChroma: 3, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'Ab', step: 7, options: ['D#', 'Eb'] } },
  { sourceTonic: 'Ab', step: 8, targetChroma: 4, expected: { status: 'ready', mode: 'minor', sourceTonic: 'Ab', step: 8, targetTonic: 'E' } },
  { sourceTonic: 'Ab', step: 9, targetChroma: 5, expected: { status: 'ready', mode: 'minor', sourceTonic: 'Ab', step: 9, targetTonic: 'F' } },
  { sourceTonic: 'Ab', step: 10, targetChroma: 6, expected: { status: 'ready', mode: 'minor', sourceTonic: 'Ab', step: 10, targetTonic: 'F#' } },
  { sourceTonic: 'Ab', step: 11, targetChroma: 7, expected: { status: 'ready', mode: 'minor', sourceTonic: 'Ab', step: 11, targetTonic: 'G' } },
  { sourceTonic: 'A', step: -11, targetChroma: 10, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'A', step: -11, options: ['A#', 'Bb'] } },
  { sourceTonic: 'A', step: -10, targetChroma: 11, expected: { status: 'ready', mode: 'minor', sourceTonic: 'A', step: -10, targetTonic: 'B' } },
  { sourceTonic: 'A', step: -9, targetChroma: 0, expected: { status: 'ready', mode: 'minor', sourceTonic: 'A', step: -9, targetTonic: 'C' } },
  { sourceTonic: 'A', step: -8, targetChroma: 1, expected: { status: 'ready', mode: 'minor', sourceTonic: 'A', step: -8, targetTonic: 'C#' } },
  { sourceTonic: 'A', step: -7, targetChroma: 2, expected: { status: 'ready', mode: 'minor', sourceTonic: 'A', step: -7, targetTonic: 'D' } },
  { sourceTonic: 'A', step: -6, targetChroma: 3, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'A', step: -6, options: ['D#', 'Eb'] } },
  { sourceTonic: 'A', step: -5, targetChroma: 4, expected: { status: 'ready', mode: 'minor', sourceTonic: 'A', step: -5, targetTonic: 'E' } },
  { sourceTonic: 'A', step: -4, targetChroma: 5, expected: { status: 'ready', mode: 'minor', sourceTonic: 'A', step: -4, targetTonic: 'F' } },
  { sourceTonic: 'A', step: -3, targetChroma: 6, expected: { status: 'ready', mode: 'minor', sourceTonic: 'A', step: -3, targetTonic: 'F#' } },
  { sourceTonic: 'A', step: -2, targetChroma: 7, expected: { status: 'ready', mode: 'minor', sourceTonic: 'A', step: -2, targetTonic: 'G' } },
  { sourceTonic: 'A', step: -1, targetChroma: 8, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'A', step: -1, options: ['G#', 'Ab'] } },
  { sourceTonic: 'A', step: 0, targetChroma: 9, expected: { status: 'ready', mode: 'minor', sourceTonic: 'A', step: 0, targetTonic: 'A' } },
  { sourceTonic: 'A', step: 1, targetChroma: 10, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'A', step: 1, options: ['A#', 'Bb'] } },
  { sourceTonic: 'A', step: 2, targetChroma: 11, expected: { status: 'ready', mode: 'minor', sourceTonic: 'A', step: 2, targetTonic: 'B' } },
  { sourceTonic: 'A', step: 3, targetChroma: 0, expected: { status: 'ready', mode: 'minor', sourceTonic: 'A', step: 3, targetTonic: 'C' } },
  { sourceTonic: 'A', step: 4, targetChroma: 1, expected: { status: 'ready', mode: 'minor', sourceTonic: 'A', step: 4, targetTonic: 'C#' } },
  { sourceTonic: 'A', step: 5, targetChroma: 2, expected: { status: 'ready', mode: 'minor', sourceTonic: 'A', step: 5, targetTonic: 'D' } },
  { sourceTonic: 'A', step: 6, targetChroma: 3, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'A', step: 6, options: ['D#', 'Eb'] } },
  { sourceTonic: 'A', step: 7, targetChroma: 4, expected: { status: 'ready', mode: 'minor', sourceTonic: 'A', step: 7, targetTonic: 'E' } },
  { sourceTonic: 'A', step: 8, targetChroma: 5, expected: { status: 'ready', mode: 'minor', sourceTonic: 'A', step: 8, targetTonic: 'F' } },
  { sourceTonic: 'A', step: 9, targetChroma: 6, expected: { status: 'ready', mode: 'minor', sourceTonic: 'A', step: 9, targetTonic: 'F#' } },
  { sourceTonic: 'A', step: 10, targetChroma: 7, expected: { status: 'ready', mode: 'minor', sourceTonic: 'A', step: 10, targetTonic: 'G' } },
  { sourceTonic: 'A', step: 11, targetChroma: 8, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'A', step: 11, options: ['G#', 'Ab'] } },
  { sourceTonic: 'A#', step: -11, targetChroma: 11, expected: { status: 'ready', mode: 'minor', sourceTonic: 'A#', step: -11, targetTonic: 'B' } },
  { sourceTonic: 'A#', step: -10, targetChroma: 0, expected: { status: 'ready', mode: 'minor', sourceTonic: 'A#', step: -10, targetTonic: 'C' } },
  { sourceTonic: 'A#', step: -9, targetChroma: 1, expected: { status: 'ready', mode: 'minor', sourceTonic: 'A#', step: -9, targetTonic: 'C#' } },
  { sourceTonic: 'A#', step: -8, targetChroma: 2, expected: { status: 'ready', mode: 'minor', sourceTonic: 'A#', step: -8, targetTonic: 'D' } },
  { sourceTonic: 'A#', step: -7, targetChroma: 3, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'A#', step: -7, options: ['D#', 'Eb'] } },
  { sourceTonic: 'A#', step: -6, targetChroma: 4, expected: { status: 'ready', mode: 'minor', sourceTonic: 'A#', step: -6, targetTonic: 'E' } },
  { sourceTonic: 'A#', step: -5, targetChroma: 5, expected: { status: 'ready', mode: 'minor', sourceTonic: 'A#', step: -5, targetTonic: 'F' } },
  { sourceTonic: 'A#', step: -4, targetChroma: 6, expected: { status: 'ready', mode: 'minor', sourceTonic: 'A#', step: -4, targetTonic: 'F#' } },
  { sourceTonic: 'A#', step: -3, targetChroma: 7, expected: { status: 'ready', mode: 'minor', sourceTonic: 'A#', step: -3, targetTonic: 'G' } },
  { sourceTonic: 'A#', step: -2, targetChroma: 8, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'A#', step: -2, options: ['G#', 'Ab'] } },
  { sourceTonic: 'A#', step: -1, targetChroma: 9, expected: { status: 'ready', mode: 'minor', sourceTonic: 'A#', step: -1, targetTonic: 'A' } },
  { sourceTonic: 'A#', step: 0, targetChroma: 10, expected: { status: 'ready', mode: 'minor', sourceTonic: 'A#', step: 0, targetTonic: 'A#' } },
  { sourceTonic: 'A#', step: 1, targetChroma: 11, expected: { status: 'ready', mode: 'minor', sourceTonic: 'A#', step: 1, targetTonic: 'B' } },
  { sourceTonic: 'A#', step: 2, targetChroma: 0, expected: { status: 'ready', mode: 'minor', sourceTonic: 'A#', step: 2, targetTonic: 'C' } },
  { sourceTonic: 'A#', step: 3, targetChroma: 1, expected: { status: 'ready', mode: 'minor', sourceTonic: 'A#', step: 3, targetTonic: 'C#' } },
  { sourceTonic: 'A#', step: 4, targetChroma: 2, expected: { status: 'ready', mode: 'minor', sourceTonic: 'A#', step: 4, targetTonic: 'D' } },
  { sourceTonic: 'A#', step: 5, targetChroma: 3, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'A#', step: 5, options: ['D#', 'Eb'] } },
  { sourceTonic: 'A#', step: 6, targetChroma: 4, expected: { status: 'ready', mode: 'minor', sourceTonic: 'A#', step: 6, targetTonic: 'E' } },
  { sourceTonic: 'A#', step: 7, targetChroma: 5, expected: { status: 'ready', mode: 'minor', sourceTonic: 'A#', step: 7, targetTonic: 'F' } },
  { sourceTonic: 'A#', step: 8, targetChroma: 6, expected: { status: 'ready', mode: 'minor', sourceTonic: 'A#', step: 8, targetTonic: 'F#' } },
  { sourceTonic: 'A#', step: 9, targetChroma: 7, expected: { status: 'ready', mode: 'minor', sourceTonic: 'A#', step: 9, targetTonic: 'G' } },
  { sourceTonic: 'A#', step: 10, targetChroma: 8, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'A#', step: 10, options: ['G#', 'Ab'] } },
  { sourceTonic: 'A#', step: 11, targetChroma: 9, expected: { status: 'ready', mode: 'minor', sourceTonic: 'A#', step: 11, targetTonic: 'A' } },
  { sourceTonic: 'Bb', step: -11, targetChroma: 11, expected: { status: 'ready', mode: 'minor', sourceTonic: 'Bb', step: -11, targetTonic: 'B' } },
  { sourceTonic: 'Bb', step: -10, targetChroma: 0, expected: { status: 'ready', mode: 'minor', sourceTonic: 'Bb', step: -10, targetTonic: 'C' } },
  { sourceTonic: 'Bb', step: -9, targetChroma: 1, expected: { status: 'ready', mode: 'minor', sourceTonic: 'Bb', step: -9, targetTonic: 'C#' } },
  { sourceTonic: 'Bb', step: -8, targetChroma: 2, expected: { status: 'ready', mode: 'minor', sourceTonic: 'Bb', step: -8, targetTonic: 'D' } },
  { sourceTonic: 'Bb', step: -7, targetChroma: 3, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'Bb', step: -7, options: ['D#', 'Eb'] } },
  { sourceTonic: 'Bb', step: -6, targetChroma: 4, expected: { status: 'ready', mode: 'minor', sourceTonic: 'Bb', step: -6, targetTonic: 'E' } },
  { sourceTonic: 'Bb', step: -5, targetChroma: 5, expected: { status: 'ready', mode: 'minor', sourceTonic: 'Bb', step: -5, targetTonic: 'F' } },
  { sourceTonic: 'Bb', step: -4, targetChroma: 6, expected: { status: 'ready', mode: 'minor', sourceTonic: 'Bb', step: -4, targetTonic: 'F#' } },
  { sourceTonic: 'Bb', step: -3, targetChroma: 7, expected: { status: 'ready', mode: 'minor', sourceTonic: 'Bb', step: -3, targetTonic: 'G' } },
  { sourceTonic: 'Bb', step: -2, targetChroma: 8, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'Bb', step: -2, options: ['G#', 'Ab'] } },
  { sourceTonic: 'Bb', step: -1, targetChroma: 9, expected: { status: 'ready', mode: 'minor', sourceTonic: 'Bb', step: -1, targetTonic: 'A' } },
  { sourceTonic: 'Bb', step: 0, targetChroma: 10, expected: { status: 'ready', mode: 'minor', sourceTonic: 'Bb', step: 0, targetTonic: 'Bb' } },
  { sourceTonic: 'Bb', step: 1, targetChroma: 11, expected: { status: 'ready', mode: 'minor', sourceTonic: 'Bb', step: 1, targetTonic: 'B' } },
  { sourceTonic: 'Bb', step: 2, targetChroma: 0, expected: { status: 'ready', mode: 'minor', sourceTonic: 'Bb', step: 2, targetTonic: 'C' } },
  { sourceTonic: 'Bb', step: 3, targetChroma: 1, expected: { status: 'ready', mode: 'minor', sourceTonic: 'Bb', step: 3, targetTonic: 'C#' } },
  { sourceTonic: 'Bb', step: 4, targetChroma: 2, expected: { status: 'ready', mode: 'minor', sourceTonic: 'Bb', step: 4, targetTonic: 'D' } },
  { sourceTonic: 'Bb', step: 5, targetChroma: 3, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'Bb', step: 5, options: ['D#', 'Eb'] } },
  { sourceTonic: 'Bb', step: 6, targetChroma: 4, expected: { status: 'ready', mode: 'minor', sourceTonic: 'Bb', step: 6, targetTonic: 'E' } },
  { sourceTonic: 'Bb', step: 7, targetChroma: 5, expected: { status: 'ready', mode: 'minor', sourceTonic: 'Bb', step: 7, targetTonic: 'F' } },
  { sourceTonic: 'Bb', step: 8, targetChroma: 6, expected: { status: 'ready', mode: 'minor', sourceTonic: 'Bb', step: 8, targetTonic: 'F#' } },
  { sourceTonic: 'Bb', step: 9, targetChroma: 7, expected: { status: 'ready', mode: 'minor', sourceTonic: 'Bb', step: 9, targetTonic: 'G' } },
  { sourceTonic: 'Bb', step: 10, targetChroma: 8, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'Bb', step: 10, options: ['G#', 'Ab'] } },
  { sourceTonic: 'Bb', step: 11, targetChroma: 9, expected: { status: 'ready', mode: 'minor', sourceTonic: 'Bb', step: 11, targetTonic: 'A' } },
  { sourceTonic: 'B', step: -11, targetChroma: 0, expected: { status: 'ready', mode: 'minor', sourceTonic: 'B', step: -11, targetTonic: 'C' } },
  { sourceTonic: 'B', step: -10, targetChroma: 1, expected: { status: 'ready', mode: 'minor', sourceTonic: 'B', step: -10, targetTonic: 'C#' } },
  { sourceTonic: 'B', step: -9, targetChroma: 2, expected: { status: 'ready', mode: 'minor', sourceTonic: 'B', step: -9, targetTonic: 'D' } },
  { sourceTonic: 'B', step: -8, targetChroma: 3, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'B', step: -8, options: ['D#', 'Eb'] } },
  { sourceTonic: 'B', step: -7, targetChroma: 4, expected: { status: 'ready', mode: 'minor', sourceTonic: 'B', step: -7, targetTonic: 'E' } },
  { sourceTonic: 'B', step: -6, targetChroma: 5, expected: { status: 'ready', mode: 'minor', sourceTonic: 'B', step: -6, targetTonic: 'F' } },
  { sourceTonic: 'B', step: -5, targetChroma: 6, expected: { status: 'ready', mode: 'minor', sourceTonic: 'B', step: -5, targetTonic: 'F#' } },
  { sourceTonic: 'B', step: -4, targetChroma: 7, expected: { status: 'ready', mode: 'minor', sourceTonic: 'B', step: -4, targetTonic: 'G' } },
  { sourceTonic: 'B', step: -3, targetChroma: 8, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'B', step: -3, options: ['G#', 'Ab'] } },
  { sourceTonic: 'B', step: -2, targetChroma: 9, expected: { status: 'ready', mode: 'minor', sourceTonic: 'B', step: -2, targetTonic: 'A' } },
  { sourceTonic: 'B', step: -1, targetChroma: 10, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'B', step: -1, options: ['A#', 'Bb'] } },
  { sourceTonic: 'B', step: 0, targetChroma: 11, expected: { status: 'ready', mode: 'minor', sourceTonic: 'B', step: 0, targetTonic: 'B' } },
  { sourceTonic: 'B', step: 1, targetChroma: 0, expected: { status: 'ready', mode: 'minor', sourceTonic: 'B', step: 1, targetTonic: 'C' } },
  { sourceTonic: 'B', step: 2, targetChroma: 1, expected: { status: 'ready', mode: 'minor', sourceTonic: 'B', step: 2, targetTonic: 'C#' } },
  { sourceTonic: 'B', step: 3, targetChroma: 2, expected: { status: 'ready', mode: 'minor', sourceTonic: 'B', step: 3, targetTonic: 'D' } },
  { sourceTonic: 'B', step: 4, targetChroma: 3, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'B', step: 4, options: ['D#', 'Eb'] } },
  { sourceTonic: 'B', step: 5, targetChroma: 4, expected: { status: 'ready', mode: 'minor', sourceTonic: 'B', step: 5, targetTonic: 'E' } },
  { sourceTonic: 'B', step: 6, targetChroma: 5, expected: { status: 'ready', mode: 'minor', sourceTonic: 'B', step: 6, targetTonic: 'F' } },
  { sourceTonic: 'B', step: 7, targetChroma: 6, expected: { status: 'ready', mode: 'minor', sourceTonic: 'B', step: 7, targetTonic: 'F#' } },
  { sourceTonic: 'B', step: 8, targetChroma: 7, expected: { status: 'ready', mode: 'minor', sourceTonic: 'B', step: 8, targetTonic: 'G' } },
  { sourceTonic: 'B', step: 9, targetChroma: 8, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'B', step: 9, options: ['G#', 'Ab'] } },
  { sourceTonic: 'B', step: 10, targetChroma: 9, expected: { status: 'ready', mode: 'minor', sourceTonic: 'B', step: 10, targetTonic: 'A' } },
  { sourceTonic: 'B', step: 11, targetChroma: 10, expected: { status: 'requiresEnharmonicChoice', mode: 'minor', sourceTonic: 'B', step: 11, options: ['A#', 'Bb'] } },
];
